-- =============================================================================
-- Migración: Catálogo Dálida Beauty & Spa (áreas + servicios con grupos e imágenes)
-- Idempotente (upsert por slug). Ejecutar en el SQL Editor de Supabase (schema spanails).
-- =============================================================================

alter table spanails.categorias add column if not exists icono text;
alter table spanails.servicios  add column if not exists grupo text;

-- ---- Áreas ----
insert into spanails.categorias (nombre, slug, descripcion, icono, orden, activo) values
  ('Estética Facial', 'estetica-facial', 'Limpiezas, hidratación, antiedad, manchas, acné y peelings.', '✨', 100, true),
  ('Medicina Estética', 'medicina-estetica', 'Procedimientos realizados por profesional médico habilitado.', '💉', 101, true),
  ('Tratamientos Corporales', 'tratamientos-corporales', 'Reductores, anticelulíticos, reafirmantes y modelado corporal.', '🌿', 102, true),
  ('Depilación', 'depilacion', 'Depilación con cera, láser e hilo para rostro y cuerpo.', '🌸', 103, true),
  ('Masajes', 'masajes', 'Masajes relajantes, terapéuticos, drenaje y especializados.', '💆‍♀️', 104, true),
  ('Spa', 'spa', 'Circuito de spa y rituales de bienestar para una experiencia completa.', '🧖‍♀️', 105, true),
  ('Exfoliaciones', 'exfoliaciones', 'Exfoliaciones corporales con ingredientes naturales premium.', '🧂', 106, true),
  ('Envolturas Corporales', 'envolturas-corporales', 'Envolturas nutritivas y detoxificantes para la piel.', '🍫', 107, true),
  ('Hidroterapia', 'hidroterapia', 'Terapias con agua, color y aromas para relajar cuerpo y mente.', '💧', 108, true),
  ('Manicura', 'manicura', 'Técnicas de manicura y decoraciones artísticas a medida.', '💅', 109, true),
  ('Pedicura', 'pedicura', 'Pedicura estética, spa y podológica para pies sanos y prolijos.', '🦶', 110, true),
  ('Cejas', 'cejas', 'Diseño, perfilado y técnicas de pigmentación de cejas.', '👁️', 111, true),
  ('Pestañas', 'pestanas', 'Lifting, tinte y extensiones para una mirada intensa.', '🦋', 112, true),
  ('Maquillaje', 'maquillaje', 'Maquillaje profesional para eventos, novias y producciones.', '💄', 113, true),
  ('Peluquería', 'peluqueria', 'Corte, color, tratamientos capilares y peinados de alta gama.', '💇‍♀️', 114, true),
  ('Barbería', 'barberia', 'Corte y arreglo de barba con estilo y detalle masculino.', '💈', 115, true),
  ('Bronceado', 'bronceado', 'Bronceado sin sol, uniforme y seguro para tu piel.', '☀️', 116, true),
  ('Bienestar', 'bienestar', 'Terapias de relajación profunda para cuerpo y mente.', '🕯️', 117, true),
  ('Programas Premium', 'programas-premium', 'Experiencias completas de spa diseñadas para ocasiones especiales.', '👑', 118, true),
  ('Servicios VIP', 'servicios-vip', 'Membresías, atención exclusiva y beneficios pensados para vos.', '⭐', 119, true)
on conflict (slug) do update set nombre=excluded.nombre, descripcion=excluded.descripcion, icono=excluded.icono, orden=excluded.orden, activo=true;

-- ---- Servicios ----
with c as (select id, slug from spanails.categorias)
insert into spanails.servicios (categoria_id, nombre, slug, grupo, imagen_url, precio, orden, activo) values
  ((select id from c where slug='estetica-facial'), 'Limpieza facial básica', 'estetica-facial-limpieza-facial-basica', 'Limpiezas faciales', '/servicios/limpieza-facial-basica.jpg', 0, 1, true),
  ((select id from c where slug='estetica-facial'), 'Limpieza facial profunda', 'estetica-facial-limpieza-facial-profunda', 'Limpiezas faciales', '/servicios/limpieza-facial-profunda.jpg', 0, 2, true),
  ((select id from c where slug='estetica-facial'), 'Limpieza ultrasónica', 'estetica-facial-limpieza-ultrasonica', 'Limpiezas faciales', '/servicios/limpieza-ultrasonica.jpg', 0, 3, true),
  ((select id from c where slug='estetica-facial'), 'Limpieza con punta de diamante', 'estetica-facial-limpieza-con-punta-de-diamante', 'Limpiezas faciales', '/servicios/limpieza-punta-diamante.jpg', 0, 4, true),
  ((select id from c where slug='estetica-facial'), 'Limpieza con espátula ultrasónica', 'estetica-facial-limpieza-con-espatula-ultrasonica', 'Limpiezas faciales', '/servicios/limpieza-espatula-ultrasonica.jpg', 0, 5, true),
  ((select id from c where slug='estetica-facial'), 'Higiene facial para piel grasa', 'estetica-facial-higiene-facial-para-piel-grasa', 'Limpiezas faciales', '/servicios/higiene-facial-piel-grasa.jpg', 0, 6, true),
  ((select id from c where slug='estetica-facial'), 'Higiene facial para piel seca', 'estetica-facial-higiene-facial-para-piel-seca', 'Limpiezas faciales', '/servicios/higiene-facial-piel-seca.jpg', 0, 7, true),
  ((select id from c where slug='estetica-facial'), 'Higiene facial para piel sensible', 'estetica-facial-higiene-facial-para-piel-sensible', 'Limpiezas faciales', '/servicios/higiene-facial-piel-sensible.jpg', 0, 8, true),
  ((select id from c where slug='estetica-facial'), 'Higiene facial masculina', 'estetica-facial-higiene-facial-masculina', 'Limpiezas faciales', '/servicios/higiene-facial-masculina.jpg', 0, 9, true),
  ((select id from c where slug='estetica-facial'), 'Limpieza para adolescentes', 'estetica-facial-limpieza-para-adolescentes', 'Limpiezas faciales', '/servicios/limpieza-adolescentes.jpg', 0, 10, true),
  ((select id from c where slug='estetica-facial'), 'Hidratación profunda', 'estetica-facial-hidratacion-profunda', 'Tratamientos hidratantes', '/servicios/hidratacion-profunda.jpg', 0, 11, true),
  ((select id from c where slug='estetica-facial'), 'Nutrición facial', 'estetica-facial-nutricion-facial', 'Tratamientos hidratantes', '/servicios/nutricion-facial.jpg', 0, 12, true),
  ((select id from c where slug='estetica-facial'), 'Oxigenoterapia', 'estetica-facial-oxigenoterapia', 'Tratamientos hidratantes', '/servicios/oxigenoterapia.jpg', 0, 13, true),
  ((select id from c where slug='estetica-facial'), 'Tratamiento calmante', 'estetica-facial-tratamiento-calmante', 'Tratamientos hidratantes', '/servicios/tratamiento-calmante.jpg', 0, 14, true),
  ((select id from c where slug='estetica-facial'), 'Tratamiento reparador', 'estetica-facial-tratamiento-reparador', 'Tratamientos hidratantes', '/servicios/tratamiento-reparador.jpg', 0, 15, true),
  ((select id from c where slug='estetica-facial'), 'Mascarillas profesionales', 'estetica-facial-mascarillas-profesionales', 'Tratamientos hidratantes', '/servicios/mascarillas-profesionales.jpg', 0, 16, true),
  ((select id from c where slug='estetica-facial'), 'Rejuvenecimiento facial', 'estetica-facial-rejuvenecimiento-facial', 'Antiedad', '/servicios/rejuvenecimiento-facial.jpg', 0, 17, true),
  ((select id from c where slug='estetica-facial'), 'Lifting facial sin cirugía', 'estetica-facial-lifting-facial-sin-cirugia', 'Antiedad', '/servicios/lifting-facial-sin-cirugia.jpg', 0, 18, true),
  ((select id from c where slug='estetica-facial'), 'Radiofrecuencia facial', 'estetica-facial-radiofrecuencia-facial', 'Antiedad', '/servicios/radiofrecuencia-facial.jpg', 0, 19, true),
  ((select id from c where slug='estetica-facial'), 'HIFU', 'estetica-facial-hifu', 'Antiedad', '/servicios/hifu.jpg', 0, 20, true),
  ((select id from c where slug='estetica-facial'), 'Microneedling (Dermapen)', 'estetica-facial-microneedling-dermapen', 'Antiedad', '/servicios/microneedling-dermapen.jpg', 0, 21, true),
  ((select id from c where slug='estetica-facial'), 'Mesoterapia virtual', 'estetica-facial-mesoterapia-virtual', 'Antiedad', '/servicios/mesoterapia-virtual.jpg', 0, 22, true),
  ((select id from c where slug='estetica-facial'), 'Electroporación', 'estetica-facial-electroporacion', 'Antiedad', '/servicios/electroporacion.jpg', 0, 23, true),
  ((select id from c where slug='estetica-facial'), 'Colágeno facial', 'estetica-facial-colageno-facial', 'Antiedad', '/servicios/colageno-facial.jpg', 0, 24, true),
  ((select id from c where slug='estetica-facial'), 'Elastina', 'estetica-facial-elastina', 'Antiedad', '/servicios/elastina.jpg', 0, 25, true),
  ((select id from c where slug='estetica-facial'), 'Fototerapia LED', 'estetica-facial-fototerapia-led', 'Antiedad', '/servicios/fototerapia-led.jpg', 0, 26, true),
  ((select id from c where slug='estetica-facial'), 'Terapia con oxígeno', 'estetica-facial-terapia-con-oxigeno', 'Antiedad', '/servicios/terapia-con-oxigeno.jpg', 0, 27, true),
  ((select id from c where slug='estetica-facial'), 'Tratamiento despigmentante', 'estetica-facial-tratamiento-despigmentante', 'Manchas', '/servicios/tratamiento-despigmentante.jpg', 0, 28, true),
  ((select id from c where slug='estetica-facial'), 'Melasma', 'estetica-facial-melasma', 'Manchas', '/servicios/melasma.jpg', 0, 29, true),
  ((select id from c where slug='estetica-facial'), 'Manchas solares', 'estetica-facial-manchas-solares', 'Manchas', '/servicios/manchas-solares.jpg', 0, 30, true),
  ((select id from c where slug='estetica-facial'), 'Manchas postacné', 'estetica-facial-manchas-postacne', 'Manchas', '/servicios/manchas-postacne.jpg', 0, 31, true),
  ((select id from c where slug='estetica-facial'), 'Peelings despigmentantes', 'estetica-facial-peelings-despigmentantes', 'Manchas', '/servicios/peelings-despigmentantes.jpg', 0, 32, true),
  ((select id from c where slug='estetica-facial'), 'Tratamiento antiacné', 'estetica-facial-tratamiento-antiacne', 'Acné', '/servicios/tratamiento-antiacne.jpg', 0, 33, true),
  ((select id from c where slug='estetica-facial'), 'Control de sebo', 'estetica-facial-control-de-sebo', 'Acné', '/servicios/control-de-sebo.jpg', 0, 34, true),
  ((select id from c where slug='estetica-facial'), 'Reducción de poros', 'estetica-facial-reduccion-de-poros', 'Acné', '/servicios/reduccion-de-poros.jpg', 0, 35, true),
  ((select id from c where slug='estetica-facial'), 'Tratamiento para cicatrices', 'estetica-facial-tratamiento-para-cicatrices', 'Acné', '/servicios/tratamiento-para-cicatrices.jpg', 0, 36, true),
  ((select id from c where slug='estetica-facial'), 'Químicos', 'estetica-facial-quimicos', 'Peelings', '/servicios/peeling-quimicos.jpg', 0, 37, true),
  ((select id from c where slug='estetica-facial'), 'Enzimáticos', 'estetica-facial-enzimaticos', 'Peelings', '/servicios/peeling-enzimaticos.jpg', 0, 38, true),
  ((select id from c where slug='estetica-facial'), 'Diamante', 'estetica-facial-diamante', 'Peelings', '/servicios/peeling-diamante.jpg', 0, 39, true),
  ((select id from c where slug='estetica-facial'), 'Carbón activado', 'estetica-facial-carbon-activado', 'Peelings', '/servicios/peeling-carbon-activado.jpg', 0, 40, true),
  ((select id from c where slug='estetica-facial'), 'Hollywood Peel', 'estetica-facial-hollywood-peel', 'Peelings', '/servicios/peeling-hollywood.jpg', 0, 41, true),
  ((select id from c where slug='medicina-estetica'), 'Toxina botulínica', 'medicina-estetica-toxina-botulinica', null, '/servicios/toxina-botulinica.jpg', 0, 1, true),
  ((select id from c where slug='medicina-estetica'), 'Ácido hialurónico', 'medicina-estetica-acido-hialuronico', null, '/servicios/acido-hialuronico.jpg', 0, 2, true),
  ((select id from c where slug='medicina-estetica'), 'Bioestimuladores', 'medicina-estetica-bioestimuladores', null, '/servicios/bioestimuladores.jpg', 0, 3, true),
  ((select id from c where slug='medicina-estetica'), 'Plasma Rico en Plaquetas', 'medicina-estetica-plasma-rico-en-plaquetas', null, '/servicios/plasma-rico-plaquetas.jpg', 0, 4, true),
  ((select id from c where slug='medicina-estetica'), 'Mesoterapia', 'medicina-estetica-mesoterapia', null, '/servicios/mesoterapia.jpg', 0, 5, true),
  ((select id from c where slug='medicina-estetica'), 'Hilos tensores', 'medicina-estetica-hilos-tensores', null, '/servicios/hilos-tensores.jpg', 0, 6, true),
  ((select id from c where slug='medicina-estetica'), 'Relleno de labios', 'medicina-estetica-relleno-de-labios', null, '/servicios/relleno-labios.jpg', 0, 7, true),
  ((select id from c where slug='medicina-estetica'), 'Perfilado mandibular', 'medicina-estetica-perfilado-mandibular', null, '/servicios/perfilado-mandibular.jpg', 0, 8, true),
  ((select id from c where slug='medicina-estetica'), 'Rinomodelación', 'medicina-estetica-rinomodelacion', null, '/servicios/rinomodelacion.jpg', 0, 9, true),
  ((select id from c where slug='medicina-estetica'), 'Biorrevitalización', 'medicina-estetica-biorrevitalizacion', null, '/servicios/biorrevitalizacion.jpg', 0, 10, true),
  ((select id from c where slug='tratamientos-corporales'), 'Criolipólisis', 'tratamientos-corporales-criolipolisis', 'Reductores', '/servicios/criolipolisis.jpg', 0, 1, true),
  ((select id from c where slug='tratamientos-corporales'), 'Cavitación', 'tratamientos-corporales-cavitacion', 'Reductores', '/servicios/cavitacion.jpg', 0, 2, true),
  ((select id from c where slug='tratamientos-corporales'), 'Lipoláser', 'tratamientos-corporales-lipolaser', 'Reductores', '/servicios/lipolaser.jpg', 0, 3, true),
  ((select id from c where slug='tratamientos-corporales'), 'Radiofrecuencia corporal', 'tratamientos-corporales-radiofrecuencia-corporal', 'Reductores', '/servicios/radiofrecuencia-corporal.jpg', 0, 4, true),
  ((select id from c where slug='tratamientos-corporales'), 'Ultrasonido', 'tratamientos-corporales-ultrasonido', 'Reductores', '/servicios/ultrasonido.jpg', 0, 5, true),
  ((select id from c where slug='tratamientos-corporales'), 'EMS Sculpt', 'tratamientos-corporales-ems-sculpt', 'Reductores', '/servicios/ems-sculpt.jpg', 0, 6, true),
  ((select id from c where slug='tratamientos-corporales'), 'Vacumterapia', 'tratamientos-corporales-vacumterapia', 'Reductores', '/servicios/vacumterapia.jpg', 0, 7, true),
  ((select id from c where slug='tratamientos-corporales'), 'Ondas rusas', 'tratamientos-corporales-ondas-rusas', 'Reductores', '/servicios/ondas-rusas.jpg', 0, 8, true),
  ((select id from c where slug='tratamientos-corporales'), 'Drenaje', 'tratamientos-corporales-drenaje', 'Celulitis', '/servicios/drenaje.jpg', 0, 9, true),
  ((select id from c where slug='tratamientos-corporales'), 'Maderoterapia', 'tratamientos-corporales-maderoterapia', 'Celulitis', '/servicios/maderoterapia.jpg', 0, 10, true),
  ((select id from c where slug='tratamientos-corporales'), 'Endermoterapia', 'tratamientos-corporales-endermoterapia', 'Celulitis', '/servicios/endermoterapia.jpg', 0, 11, true),
  ((select id from c where slug='tratamientos-corporales'), 'Presoterapia', 'tratamientos-corporales-presoterapia', 'Celulitis', '/servicios/presoterapia.jpg', 0, 12, true),
  ((select id from c where slug='tratamientos-corporales'), 'Anticelulítico intensivo', 'tratamientos-corporales-anticelulitico-intensivo', 'Celulitis', '/servicios/anticelulitico-intensivo.jpg', 0, 13, true),
  ((select id from c where slug='tratamientos-corporales'), 'Radiofrecuencia', 'tratamientos-corporales-radiofrecuencia', 'Flacidez', '/servicios/flacidez-radiofrecuencia.jpg', 0, 14, true),
  ((select id from c where slug='tratamientos-corporales'), 'HIFU corporal', 'tratamientos-corporales-hifu-corporal', 'Flacidez', '/servicios/hifu-corporal.jpg', 0, 15, true),
  ((select id from c where slug='tratamientos-corporales'), 'Electroestimulación', 'tratamientos-corporales-electroestimulacion', 'Flacidez', '/servicios/electroestimulacion.jpg', 0, 16, true),
  ((select id from c where slug='tratamientos-corporales'), 'Colágeno corporal', 'tratamientos-corporales-colageno-corporal', 'Flacidez', '/servicios/colageno-corporal.jpg', 0, 17, true),
  ((select id from c where slug='tratamientos-corporales'), 'Microneedling', 'tratamientos-corporales-microneedling', 'Estrías', '/servicios/microneedling-corporal.jpg', 0, 18, true),
  ((select id from c where slug='tratamientos-corporales'), 'Plasma', 'tratamientos-corporales-plasma', 'Estrías', '/servicios/plasma-corporal.jpg', 0, 19, true),
  ((select id from c where slug='tratamientos-corporales'), 'Láser', 'tratamientos-corporales-laser', 'Estrías', '/servicios/laser-corporal.jpg', 0, 20, true),
  ((select id from c where slug='tratamientos-corporales'), 'Peelings', 'tratamientos-corporales-peelings', 'Estrías', '/servicios/peelings-corporal.jpg', 0, 21, true),
  ((select id from c where slug='tratamientos-corporales'), 'Remodelación', 'tratamientos-corporales-remodelacion', 'Modelado corporal', '/servicios/remodelacion.jpg', 0, 22, true),
  ((select id from c where slug='tratamientos-corporales'), 'Tonificación', 'tratamientos-corporales-tonificacion', 'Modelado corporal', '/servicios/tonificacion.jpg', 0, 23, true),
  ((select id from c where slug='tratamientos-corporales'), 'Esculpido corporal', 'tratamientos-corporales-esculpido-corporal', 'Modelado corporal', '/servicios/esculpido-corporal.jpg', 0, 24, true),
  ((select id from c where slug='tratamientos-corporales'), 'Levantamiento de glúteos', 'tratamientos-corporales-levantamiento-de-gluteos', 'Modelado corporal', '/servicios/levantamiento-gluteos.jpg', 0, 25, true),
  ((select id from c where slug='depilacion'), 'Facial', 'depilacion-facial', 'Cera', '/servicios/depilacion-facial.jpg', 0, 1, true),
  ((select id from c where slug='depilacion'), 'Axilas', 'depilacion-axilas', 'Cera', '/servicios/depilacion-axilas.jpg', 0, 2, true),
  ((select id from c where slug='depilacion'), 'Brazos', 'depilacion-brazos', 'Cera', '/servicios/depilacion-brazos.jpg', 0, 3, true),
  ((select id from c where slug='depilacion'), 'Piernas', 'depilacion-piernas', 'Cera', '/servicios/depilacion-piernas.jpg', 0, 4, true),
  ((select id from c where slug='depilacion'), 'Espalda', 'depilacion-espalda', 'Cera', '/servicios/depilacion-espalda.jpg', 0, 5, true),
  ((select id from c where slug='depilacion'), 'Abdomen', 'depilacion-abdomen', 'Cera', '/servicios/depilacion-abdomen.jpg', 0, 6, true),
  ((select id from c where slug='depilacion'), 'Bikini', 'depilacion-bikini', 'Cera', '/servicios/depilacion-bikini.jpg', 0, 7, true),
  ((select id from c where slug='depilacion'), 'Brasileña', 'depilacion-brasilena', 'Cera', '/servicios/depilacion-brasilena.jpg', 0, 8, true),
  ((select id from c where slug='depilacion'), 'Íntima', 'depilacion-intima', 'Cera', '/servicios/depilacion-intima.jpg', 0, 9, true),
  ((select id from c where slug='depilacion'), 'Diodo', 'depilacion-diodo', 'Láser', '/servicios/depilacion-diodo.jpg', 0, 10, true),
  ((select id from c where slug='depilacion'), 'Alexandrita', 'depilacion-alexandrita', 'Láser', '/servicios/depilacion-alexandrita.jpg', 0, 11, true),
  ((select id from c where slug='depilacion'), 'IPL', 'depilacion-ipl', 'Láser', '/servicios/depilacion-ipl.jpg', 0, 12, true),
  ((select id from c where slug='depilacion'), 'Cejas', 'depilacion-cejas', 'Hilo', '/servicios/depilacion-hilo-cejas.jpg', 0, 13, true),
  ((select id from c where slug='depilacion'), 'Rostro', 'depilacion-rostro', 'Hilo', '/servicios/depilacion-hilo-rostro.jpg', 0, 14, true),
  ((select id from c where slug='depilacion'), 'Labio', 'depilacion-labio', 'Hilo', '/servicios/depilacion-hilo-labio.jpg', 0, 15, true),
  ((select id from c where slug='masajes'), 'Sueco', 'masajes-sueco', 'Relajantes', '/servicios/masaje-sueco.jpg', 0, 1, true),
  ((select id from c where slug='masajes'), 'Aromaterapia', 'masajes-aromaterapia', 'Relajantes', '/servicios/masaje-aromaterapia.jpg', 0, 2, true),
  ((select id from c where slug='masajes'), 'Piedras calientes', 'masajes-piedras-calientes', 'Relajantes', '/servicios/masaje-piedras-calientes.jpg', 0, 3, true),
  ((select id from c where slug='masajes'), 'Velas', 'masajes-velas', 'Relajantes', '/servicios/masaje-velas.jpg', 0, 4, true),
  ((select id from c where slug='masajes'), 'Bambuterapia', 'masajes-bambuterapia', 'Relajantes', '/servicios/masaje-bambuterapia.jpg', 0, 5, true),
  ((select id from c where slug='masajes'), 'Descontracturante', 'masajes-descontracturante', 'Terapéuticos', '/servicios/masaje-descontracturante.jpg', 0, 6, true),
  ((select id from c where slug='masajes'), 'Deportivo', 'masajes-deportivo', 'Terapéuticos', '/servicios/masaje-deportivo.jpg', 0, 7, true),
  ((select id from c where slug='masajes'), 'Cervical', 'masajes-cervical', 'Terapéuticos', '/servicios/masaje-cervical.jpg', 0, 8, true),
  ((select id from c where slug='masajes'), 'Lumbar', 'masajes-lumbar', 'Terapéuticos', '/servicios/masaje-lumbar.jpg', 0, 9, true),
  ((select id from c where slug='masajes'), 'Espalda completa', 'masajes-espalda-completa', 'Terapéuticos', '/servicios/masaje-espalda-completa.jpg', 0, 10, true),
  ((select id from c where slug='masajes'), 'Manual', 'masajes-manual', 'Drenaje', '/servicios/masaje-manual.jpg', 0, 11, true),
  ((select id from c where slug='masajes'), 'Linfático', 'masajes-linfatico', 'Drenaje', '/servicios/masaje-linfatico.jpg', 0, 12, true),
  ((select id from c where slug='masajes'), 'Postoperatorio', 'masajes-postoperatorio', 'Drenaje', '/servicios/masaje-postoperatorio.jpg', 0, 13, true),
  ((select id from c where slug='masajes'), 'Prenatal', 'masajes-prenatal', 'Especializados', '/servicios/masaje-prenatal.jpg', 0, 14, true),
  ((select id from c where slug='masajes'), 'Posparto', 'masajes-posparto', 'Especializados', '/servicios/masaje-posparto.jpg', 0, 15, true),
  ((select id from c where slug='masajes'), 'Reflexología', 'masajes-reflexologia', 'Especializados', '/servicios/masaje-reflexologia.jpg', 0, 16, true),
  ((select id from c where slug='masajes'), 'Craneofacial', 'masajes-craneofacial', 'Especializados', '/servicios/masaje-craneofacial.jpg', 0, 17, true),
  ((select id from c where slug='spa'), 'Sauna seco', 'spa-sauna-seco', 'Circuito Spa', '/servicios/spa-sauna-seco.jpg', 0, 1, true),
  ((select id from c where slug='spa'), 'Sauna húmedo', 'spa-sauna-humedo', 'Circuito Spa', '/servicios/spa-sauna-humedo.jpg', 0, 2, true),
  ((select id from c where slug='spa'), 'Baño turco', 'spa-bano-turco', 'Circuito Spa', '/servicios/spa-bano-turco.jpg', 0, 3, true),
  ((select id from c where slug='spa'), 'Jacuzzi', 'spa-jacuzzi', 'Circuito Spa', '/servicios/spa-jacuzzi.jpg', 0, 4, true),
  ((select id from c where slug='spa'), 'Hidromasaje', 'spa-hidromasaje', 'Circuito Spa', '/servicios/spa-hidromasaje.jpg', 0, 5, true),
  ((select id from c where slug='spa'), 'Piscina climatizada', 'spa-piscina-climatizada', 'Circuito Spa', '/servicios/spa-piscina-climatizada.jpg', 0, 6, true),
  ((select id from c where slug='spa'), 'Duchas sensoriales', 'spa-duchas-sensoriales', 'Circuito Spa', '/servicios/spa-duchas-sensoriales.jpg', 0, 7, true),
  ((select id from c where slug='spa'), 'Sala de relajación', 'spa-sala-de-relajacion', 'Circuito Spa', '/servicios/spa-sala-relajacion.jpg', 0, 8, true),
  ((select id from c where slug='spa'), 'Ritual relajante', 'spa-ritual-relajante', 'Rituales Spa', '/servicios/spa-ritual-relajante.jpg', 0, 9, true),
  ((select id from c where slug='spa'), 'Ritual romántico', 'spa-ritual-romantico', 'Rituales Spa', '/servicios/spa-ritual-romantico.jpg', 0, 10, true),
  ((select id from c where slug='spa'), 'Ritual para parejas', 'spa-ritual-para-parejas', 'Rituales Spa', '/servicios/spa-ritual-parejas.jpg', 0, 11, true),
  ((select id from c where slug='spa'), 'Ritual antiestrés', 'spa-ritual-antiestres', 'Rituales Spa', '/servicios/spa-ritual-antiestres.jpg', 0, 12, true),
  ((select id from c where slug='spa'), 'Ritual detox', 'spa-ritual-detox', 'Rituales Spa', '/servicios/spa-ritual-detox.jpg', 0, 13, true),
  ((select id from c where slug='spa'), 'Ritual premium', 'spa-ritual-premium', 'Rituales Spa', '/servicios/spa-ritual-premium.jpg', 0, 14, true),
  ((select id from c where slug='spa'), 'Ritual ejecutivo', 'spa-ritual-ejecutivo', 'Rituales Spa', '/servicios/spa-ritual-ejecutivo.jpg', 0, 15, true),
  ((select id from c where slug='spa'), 'Ritual bridal', 'spa-ritual-bridal', 'Rituales Spa', '/servicios/spa-ritual-bridal.jpg', 0, 16, true),
  ((select id from c where slug='exfoliaciones'), 'Sal marina', 'exfoliaciones-sal-marina', null, '/servicios/exfoliacion-sal-marina.jpg', 0, 1, true),
  ((select id from c where slug='exfoliaciones'), 'Azúcar', 'exfoliaciones-azucar', null, '/servicios/exfoliacion-azucar.jpg', 0, 2, true),
  ((select id from c where slug='exfoliaciones'), 'Café', 'exfoliaciones-cafe', null, '/servicios/exfoliacion-cafe.jpg', 0, 3, true),
  ((select id from c where slug='exfoliaciones'), 'Chocolate', 'exfoliaciones-chocolate', null, '/servicios/exfoliacion-chocolate.jpg', 0, 4, true),
  ((select id from c where slug='exfoliaciones'), 'Coco', 'exfoliaciones-coco', null, '/servicios/exfoliacion-coco.jpg', 0, 5, true),
  ((select id from c where slug='exfoliaciones'), 'Vino', 'exfoliaciones-vino', null, '/servicios/exfoliacion-vino.jpg', 0, 6, true),
  ((select id from c where slug='exfoliaciones'), 'Oro', 'exfoliaciones-oro', null, '/servicios/exfoliacion-oro.jpg', 0, 7, true),
  ((select id from c where slug='exfoliaciones'), 'Perlas', 'exfoliaciones-perlas', null, '/servicios/exfoliacion-perlas.jpg', 0, 8, true),
  ((select id from c where slug='exfoliaciones'), 'Sales del Himalaya', 'exfoliaciones-sales-del-himalaya', null, '/servicios/exfoliacion-sales-himalaya.jpg', 0, 9, true),
  ((select id from c where slug='envolturas-corporales'), 'Chocolate', 'envolturas-corporales-chocolate', null, '/servicios/envoltura-chocolate.jpg', 0, 1, true),
  ((select id from c where slug='envolturas-corporales'), 'Algas', 'envolturas-corporales-algas', null, '/servicios/envoltura-algas.jpg', 0, 2, true),
  ((select id from c where slug='envolturas-corporales'), 'Fango', 'envolturas-corporales-fango', null, '/servicios/envoltura-fango.jpg', 0, 3, true),
  ((select id from c where slug='envolturas-corporales'), 'Barro volcánico', 'envolturas-corporales-barro-volcanico', null, '/servicios/envoltura-barro-volcanico.jpg', 0, 4, true),
  ((select id from c where slug='envolturas-corporales'), 'Arcillas', 'envolturas-corporales-arcillas', null, '/servicios/envoltura-arcillas.jpg', 0, 5, true),
  ((select id from c where slug='envolturas-corporales'), 'Vino', 'envolturas-corporales-vino', null, '/servicios/envoltura-vino.jpg', 0, 6, true),
  ((select id from c where slug='envolturas-corporales'), 'Oro', 'envolturas-corporales-oro', null, '/servicios/envoltura-oro.jpg', 0, 7, true),
  ((select id from c where slug='envolturas-corporales'), 'Café', 'envolturas-corporales-cafe', null, '/servicios/envoltura-cafe.jpg', 0, 8, true),
  ((select id from c where slug='envolturas-corporales'), 'Aloe vera', 'envolturas-corporales-aloe-vera', null, '/servicios/envoltura-aloe-vera.jpg', 0, 9, true),
  ((select id from c where slug='hidroterapia'), 'Hidromasaje', 'hidroterapia-hidromasaje', null, '/servicios/hidroterapia-hidromasaje.jpg', 0, 1, true),
  ((select id from c where slug='hidroterapia'), 'Cromoterapia', 'hidroterapia-cromoterapia', null, '/servicios/hidroterapia-cromoterapia.jpg', 0, 2, true),
  ((select id from c where slug='hidroterapia'), 'Aromaterapia', 'hidroterapia-aromaterapia', null, '/servicios/hidroterapia-aromaterapia.jpg', 0, 3, true),
  ((select id from c where slug='hidroterapia'), 'Baños minerales', 'hidroterapia-banos-minerales', null, '/servicios/hidroterapia-banos-minerales.jpg', 0, 4, true),
  ((select id from c where slug='hidroterapia'), 'Baños de leche', 'hidroterapia-banos-de-leche', null, '/servicios/hidroterapia-banos-leche.jpg', 0, 5, true),
  ((select id from c where slug='hidroterapia'), 'Sales aromáticas', 'hidroterapia-sales-aromaticas', null, '/servicios/hidroterapia-sales-aromaticas.jpg', 0, 6, true),
  ((select id from c where slug='manicura'), 'Tradicional', 'manicura-tradicional', 'Técnicas', '/servicios/manicura-tradicional.jpg', 0, 1, true),
  ((select id from c where slug='manicura'), 'Spa', 'manicura-spa', 'Técnicas', '/servicios/manicura-spa.jpg', 0, 2, true),
  ((select id from c where slug='manicura'), 'Francesa', 'manicura-francesa', 'Técnicas', '/servicios/manicura-francesa.jpg', 0, 3, true),
  ((select id from c where slug='manicura'), 'Semipermanente', 'manicura-semipermanente', 'Técnicas', '/servicios/manicura-semipermanente.jpg', 0, 4, true),
  ((select id from c where slug='manicura'), 'Gel', 'manicura-gel', 'Técnicas', '/servicios/manicura-gel.jpg', 0, 5, true),
  ((select id from c where slug='manicura'), 'Polygel', 'manicura-polygel', 'Técnicas', '/servicios/manicura-polygel.jpg', 0, 6, true),
  ((select id from c where slug='manicura'), 'Acrílicas', 'manicura-acrilicas', 'Técnicas', '/servicios/manicura-acrilicas.jpg', 0, 7, true),
  ((select id from c where slug='manicura'), 'Soft Gel', 'manicura-soft-gel', 'Técnicas', '/servicios/manicura-soft-gel.jpg', 0, 8, true),
  ((select id from c where slug='manicura'), 'Rubber Base', 'manicura-rubber-base', 'Técnicas', '/servicios/manicura-rubber-base.jpg', 0, 9, true),
  ((select id from c where slug='manicura'), 'Press On', 'manicura-press-on', 'Técnicas', '/servicios/manicura-press-on.jpg', 0, 10, true),
  ((select id from c where slug='manicura'), 'Kapping', 'manicura-kapping', 'Técnicas', '/servicios/manicura-kapping.jpg', 0, 11, true),
  ((select id from c where slug='manicura'), 'Esculpidas', 'manicura-esculpidas', 'Técnicas', '/servicios/manicura-esculpidas.jpg', 0, 12, true),
  ((select id from c where slug='manicura'), 'Nail Art', 'manicura-nail-art', 'Decoraciones', '/servicios/manicura-nail-art.jpg', 0, 13, true),
  ((select id from c where slug='manicura'), 'Cristales Swarovski', 'manicura-cristales-swarovski', 'Decoraciones', '/servicios/manicura-cristales-swarovski.jpg', 0, 14, true),
  ((select id from c where slug='manicura'), 'Efecto espejo', 'manicura-efecto-espejo', 'Decoraciones', '/servicios/manicura-efecto-espejo.jpg', 0, 15, true),
  ((select id from c where slug='manicura'), 'Baby Boomer', 'manicura-baby-boomer', 'Decoraciones', '/servicios/manicura-baby-boomer.jpg', 0, 16, true),
  ((select id from c where slug='manicura'), 'Ojo de gato', 'manicura-ojo-de-gato', 'Decoraciones', '/servicios/manicura-ojo-de-gato.jpg', 0, 17, true),
  ((select id from c where slug='manicura'), 'Encapsulados', 'manicura-encapsulados', 'Decoraciones', '/servicios/manicura-encapsulados.jpg', 0, 18, true),
  ((select id from c where slug='manicura'), 'Foil', 'manicura-foil', 'Decoraciones', '/servicios/manicura-foil.jpg', 0, 19, true),
  ((select id from c where slug='manicura'), 'Acuarela', 'manicura-acuarela', 'Decoraciones', '/servicios/manicura-acuarela.jpg', 0, 20, true),
  ((select id from c where slug='manicura'), '3D', 'manicura-3d', 'Decoraciones', '/servicios/manicura-3d.jpg', 0, 21, true),
  ((select id from c where slug='pedicura'), 'Tradicional', 'pedicura-tradicional', null, '/servicios/pedicura-tradicional.jpg', 0, 1, true),
  ((select id from c where slug='pedicura'), 'Spa', 'pedicura-spa', null, '/servicios/pedicura-spa.jpg', 0, 2, true),
  ((select id from c where slug='pedicura'), 'Podológica', 'pedicura-podologica', null, '/servicios/pedicura-podologica.jpg', 0, 3, true),
  ((select id from c where slug='pedicura'), 'Semipermanente', 'pedicura-semipermanente', null, '/servicios/pedicura-semipermanente.jpg', 0, 4, true),
  ((select id from c where slug='pedicura'), 'Gel', 'pedicura-gel', null, '/servicios/pedicura-gel.jpg', 0, 5, true),
  ((select id from c where slug='pedicura'), 'Callosidades', 'pedicura-callosidades', null, '/servicios/pedicura-callosidades.jpg', 0, 6, true),
  ((select id from c where slug='pedicura'), 'Talones agrietados', 'pedicura-talones-agrietados', null, '/servicios/pedicura-talones-agrietados.jpg', 0, 7, true),
  ((select id from c where slug='pedicura'), 'Parafina', 'pedicura-parafina', null, '/servicios/pedicura-parafina.jpg', 0, 8, true),
  ((select id from c where slug='pedicura'), 'Reflexología podal', 'pedicura-reflexologia-podal', null, '/servicios/pedicura-reflexologia-podal.jpg', 0, 9, true),
  ((select id from c where slug='cejas'), 'Diseño', 'cejas-diseno', null, '/servicios/cejas-diseno.jpg', 0, 1, true),
  ((select id from c where slug='cejas'), 'Perfilado', 'cejas-perfilado', null, '/servicios/cejas-perfilado.jpg', 0, 2, true),
  ((select id from c where slug='cejas'), 'Depilación', 'cejas-depilacion', null, '/servicios/cejas-depilacion.jpg', 0, 3, true),
  ((select id from c where slug='cejas'), 'Hilo', 'cejas-hilo', null, '/servicios/cejas-hilo.jpg', 0, 4, true),
  ((select id from c where slug='cejas'), 'Pinza', 'cejas-pinza', null, '/servicios/cejas-pinza.jpg', 0, 5, true),
  ((select id from c where slug='cejas'), 'Henna', 'cejas-henna', null, '/servicios/cejas-henna.jpg', 0, 6, true),
  ((select id from c where slug='cejas'), 'Laminado', 'cejas-laminado', null, '/servicios/cejas-laminado.jpg', 0, 7, true),
  ((select id from c where slug='cejas'), 'Microblading', 'cejas-microblading', null, '/servicios/cejas-microblading.jpg', 0, 8, true),
  ((select id from c where slug='cejas'), 'Micropigmentación', 'cejas-micropigmentacion', null, '/servicios/cejas-micropigmentacion.jpg', 0, 9, true),
  ((select id from c where slug='cejas'), 'Powder Brows', 'cejas-powder-brows', null, '/servicios/cejas-powder-brows.jpg', 0, 10, true),
  ((select id from c where slug='pestanas'), 'Lifting', 'pestanas-lifting', null, '/servicios/pestanas-lifting.jpg', 0, 1, true),
  ((select id from c where slug='pestanas'), 'Permanente', 'pestanas-permanente', null, '/servicios/pestanas-permanente.jpg', 0, 2, true),
  ((select id from c where slug='pestanas'), 'Tinte', 'pestanas-tinte', null, '/servicios/pestanas-tinte.jpg', 0, 3, true),
  ((select id from c where slug='pestanas'), 'Extensiones clásicas', 'pestanas-extensiones-clasicas', null, '/servicios/pestanas-extensiones-clasicas.jpg', 0, 4, true),
  ((select id from c where slug='pestanas'), 'Volumen ruso', 'pestanas-volumen-ruso', null, '/servicios/pestanas-volumen-ruso.jpg', 0, 5, true),
  ((select id from c where slug='pestanas'), 'Mega volumen', 'pestanas-mega-volumen', null, '/servicios/pestanas-mega-volumen.jpg', 0, 6, true),
  ((select id from c where slug='pestanas'), 'Híbridas', 'pestanas-hibridas', null, '/servicios/pestanas-hibridas.jpg', 0, 7, true),
  ((select id from c where slug='pestanas'), 'Fox Eyes', 'pestanas-fox-eyes', null, '/servicios/pestanas-fox-eyes.jpg', 0, 8, true),
  ((select id from c where slug='pestanas'), 'Wispy', 'pestanas-wispy', null, '/servicios/pestanas-wispy.jpg', 0, 9, true),
  ((select id from c where slug='pestanas'), 'Retoques', 'pestanas-retoques', null, '/servicios/pestanas-retoques.jpg', 0, 10, true),
  ((select id from c where slug='maquillaje'), 'Social', 'maquillaje-social', null, '/servicios/maquillaje-social.jpg', 0, 1, true),
  ((select id from c where slug='maquillaje'), 'Novias', 'maquillaje-novias', null, '/servicios/maquillaje-novias.jpg', 0, 2, true),
  ((select id from c where slug='maquillaje'), 'Madrinas', 'maquillaje-madrinas', null, '/servicios/maquillaje-madrinas.jpg', 0, 3, true),
  ((select id from c where slug='maquillaje'), 'Fiesta', 'maquillaje-fiesta', null, '/servicios/maquillaje-fiesta.jpg', 0, 4, true),
  ((select id from c where slug='maquillaje'), 'Editorial', 'maquillaje-editorial', null, '/servicios/maquillaje-editorial.jpg', 0, 5, true),
  ((select id from c where slug='maquillaje'), 'Fotografía', 'maquillaje-fotografia', null, '/servicios/maquillaje-fotografia.jpg', 0, 6, true),
  ((select id from c where slug='maquillaje'), 'Televisión', 'maquillaje-television', null, '/servicios/maquillaje-television.jpg', 0, 7, true),
  ((select id from c where slug='maquillaje'), 'Corporativo', 'maquillaje-corporativo', null, '/servicios/maquillaje-corporativo.jpg', 0, 8, true),
  ((select id from c where slug='maquillaje'), 'Halloween', 'maquillaje-halloween', null, '/servicios/maquillaje-halloween.jpg', 0, 9, true),
  ((select id from c where slug='maquillaje'), 'Artístico', 'maquillaje-artistico', null, '/servicios/maquillaje-artistico.jpg', 0, 10, true),
  ((select id from c where slug='maquillaje'), 'Infantil', 'maquillaje-infantil', null, '/servicios/maquillaje-infantil.jpg', 0, 11, true),
  ((select id from c where slug='peluqueria'), 'Mujer', 'peluqueria-mujer', 'Corte', '/servicios/peluqueria-corte-mujer.jpg', 0, 1, true),
  ((select id from c where slug='peluqueria'), 'Hombre', 'peluqueria-hombre', 'Corte', '/servicios/peluqueria-corte-hombre.jpg', 0, 2, true),
  ((select id from c where slug='peluqueria'), 'Niño', 'peluqueria-nino', 'Corte', '/servicios/peluqueria-corte-nino.jpg', 0, 3, true),
  ((select id from c where slug='peluqueria'), 'Tinte', 'peluqueria-tinte', 'Color', '/servicios/peluqueria-tinte.jpg', 0, 4, true),
  ((select id from c where slug='peluqueria'), 'Balayage', 'peluqueria-balayage', 'Color', '/servicios/peluqueria-balayage.jpg', 0, 5, true),
  ((select id from c where slug='peluqueria'), 'Babylights', 'peluqueria-babylights', 'Color', '/servicios/peluqueria-babylights.jpg', 0, 6, true),
  ((select id from c where slug='peluqueria'), 'Mechas', 'peluqueria-mechas', 'Color', '/servicios/peluqueria-mechas.jpg', 0, 7, true),
  ((select id from c where slug='peluqueria'), 'Ombre', 'peluqueria-ombre', 'Color', '/servicios/peluqueria-ombre.jpg', 0, 8, true),
  ((select id from c where slug='peluqueria'), 'Corrección de color', 'peluqueria-correccion-de-color', 'Color', '/servicios/peluqueria-correccion-color.jpg', 0, 9, true),
  ((select id from c where slug='peluqueria'), 'Matización', 'peluqueria-matizacion', 'Color', '/servicios/peluqueria-matizacion.jpg', 0, 10, true),
  ((select id from c where slug='peluqueria'), 'Decoloración', 'peluqueria-decoloracion', 'Color', '/servicios/peluqueria-decoloracion.jpg', 0, 11, true),
  ((select id from c where slug='peluqueria'), 'Botox capilar', 'peluqueria-botox-capilar', 'Tratamientos', '/servicios/peluqueria-botox-capilar.jpg', 0, 12, true),
  ((select id from c where slug='peluqueria'), 'Keratina', 'peluqueria-keratina', 'Tratamientos', '/servicios/peluqueria-keratina.jpg', 0, 13, true),
  ((select id from c where slug='peluqueria'), 'Hidratación', 'peluqueria-hidratacion', 'Tratamientos', '/servicios/peluqueria-hidratacion.jpg', 0, 14, true),
  ((select id from c where slug='peluqueria'), 'Colágeno', 'peluqueria-colageno', 'Tratamientos', '/servicios/peluqueria-colageno.jpg', 0, 15, true),
  ((select id from c where slug='peluqueria'), 'Ácido hialurónico capilar', 'peluqueria-acido-hialuronico-capilar', 'Tratamientos', '/servicios/peluqueria-acido-hialuronico-capilar.jpg', 0, 16, true),
  ((select id from c where slug='peluqueria'), 'Reconstrucción', 'peluqueria-reconstruccion', 'Tratamientos', '/servicios/peluqueria-reconstruccion.jpg', 0, 17, true),
  ((select id from c where slug='peluqueria'), 'Células madre', 'peluqueria-celulas-madre', 'Tratamientos', '/servicios/peluqueria-celulas-madre.jpg', 0, 18, true),
  ((select id from c where slug='peluqueria'), 'Ampollas', 'peluqueria-ampollas', 'Tratamientos', '/servicios/peluqueria-ampollas.jpg', 0, 19, true),
  ((select id from c where slug='peluqueria'), 'Brushing', 'peluqueria-brushing', 'Peinados', '/servicios/peluqueria-brushing.jpg', 0, 20, true),
  ((select id from c where slug='peluqueria'), 'Ondas', 'peluqueria-ondas', 'Peinados', '/servicios/peluqueria-ondas.jpg', 0, 21, true),
  ((select id from c where slug='peluqueria'), 'Recogidos', 'peluqueria-recogidos', 'Peinados', '/servicios/peluqueria-recogidos.jpg', 0, 22, true),
  ((select id from c where slug='peluqueria'), 'Novias', 'peluqueria-novias', 'Peinados', '/servicios/peluqueria-peinado-novias.jpg', 0, 23, true),
  ((select id from c where slug='peluqueria'), 'Trenzas', 'peluqueria-trenzas', 'Peinados', '/servicios/peluqueria-trenzas.jpg', 0, 24, true),
  ((select id from c where slug='peluqueria'), 'Eventos', 'peluqueria-eventos', 'Peinados', '/servicios/peluqueria-eventos.jpg', 0, 25, true),
  ((select id from c where slug='barberia'), 'Corte', 'barberia-corte', null, '/servicios/barberia-corte.jpg', 0, 1, true),
  ((select id from c where slug='barberia'), 'Barba', 'barberia-barba', null, '/servicios/barberia-barba.jpg', 0, 2, true),
  ((select id from c where slug='barberia'), 'Perfilado', 'barberia-perfilado', null, '/servicios/barberia-perfilado.jpg', 0, 3, true),
  ((select id from c where slug='barberia'), 'Toallas calientes', 'barberia-toallas-calientes', null, '/servicios/barberia-toallas-calientes.jpg', 0, 4, true),
  ((select id from c where slug='barberia'), 'Camuflaje de canas', 'barberia-camuflaje-de-canas', null, '/servicios/barberia-camuflaje-canas.jpg', 0, 5, true),
  ((select id from c where slug='barberia'), 'Limpieza facial masculina', 'barberia-limpieza-facial-masculina', null, '/servicios/barberia-limpieza-facial-masculina.jpg', 0, 6, true),
  ((select id from c where slug='bronceado'), 'Spray tan', 'bronceado-spray-tan', null, '/servicios/bronceado-spray-tan.jpg', 0, 1, true),
  ((select id from c where slug='bronceado'), 'Autobronceado', 'bronceado-autobronceado', null, '/servicios/bronceado-autobronceado.jpg', 0, 2, true),
  ((select id from c where slug='bronceado'), 'Bronceado DHA', 'bronceado-bronceado-dha', null, '/servicios/bronceado-dha.jpg', 0, 3, true),
  ((select id from c where slug='bienestar'), 'Aromaterapia', 'bienestar-aromaterapia', null, '/servicios/bienestar-aromaterapia.jpg', 0, 1, true),
  ((select id from c where slug='bienestar'), 'Musicoterapia', 'bienestar-musicoterapia', null, '/servicios/bienestar-musicoterapia.jpg', 0, 2, true),
  ((select id from c where slug='bienestar'), 'Cromoterapia', 'bienestar-cromoterapia', null, '/servicios/bienestar-cromoterapia.jpg', 0, 3, true),
  ((select id from c where slug='bienestar'), 'Meditación guiada', 'bienestar-meditacion-guiada', null, '/servicios/bienestar-meditacion-guiada.jpg', 0, 4, true),
  ((select id from c where slug='bienestar'), 'Mindfulness', 'bienestar-mindfulness', null, '/servicios/bienestar-mindfulness.jpg', 0, 5, true),
  ((select id from c where slug='bienestar'), 'Relajación profunda', 'bienestar-relajacion-profunda', null, '/servicios/bienestar-relajacion-profunda.jpg', 0, 6, true),
  ((select id from c where slug='programas-premium'), 'Spa para parejas', 'programas-premium-spa-para-parejas', null, '/servicios/programa-spa-parejas.jpg', 0, 1, true),
  ((select id from c where slug='programas-premium'), 'Día de princesa', 'programas-premium-dia-de-princesa', null, '/servicios/programa-dia-princesa.jpg', 0, 2, true),
  ((select id from c where slug='programas-premium'), 'Día de reina', 'programas-premium-dia-de-reina', null, '/servicios/programa-dia-reina.jpg', 0, 3, true),
  ((select id from c where slug='programas-premium'), 'Bridal Spa', 'programas-premium-bridal-spa', null, '/servicios/programa-bridal-spa.jpg', 0, 4, true),
  ((select id from c where slug='programas-premium'), 'Cumpleaños Spa', 'programas-premium-cumpleanos-spa', null, '/servicios/programa-cumpleanos-spa.jpg', 0, 5, true),
  ((select id from c where slug='programas-premium'), 'Spa corporativo', 'programas-premium-spa-corporativo', null, '/servicios/programa-spa-corporativo.jpg', 0, 6, true),
  ((select id from c where slug='programas-premium'), 'Spa ejecutivo', 'programas-premium-spa-ejecutivo', null, '/servicios/programa-spa-ejecutivo.jpg', 0, 7, true),
  ((select id from c where slug='programas-premium'), 'Spa mamá e hija', 'programas-premium-spa-mama-e-hija', null, '/servicios/programa-spa-mama-hija.jpg', 0, 8, true),
  ((select id from c where slug='programas-premium'), 'Spa prenatal', 'programas-premium-spa-prenatal', null, '/servicios/programa-spa-prenatal.jpg', 0, 9, true),
  ((select id from c where slug='programas-premium'), 'Spa postparto', 'programas-premium-spa-postparto', null, '/servicios/programa-spa-postparto.jpg', 0, 10, true),
  ((select id from c where slug='programas-premium'), 'Spa masculino', 'programas-premium-spa-masculino', null, '/servicios/programa-spa-masculino.jpg', 0, 11, true),
  ((select id from c where slug='servicios-vip'), 'Membresías', 'servicios-vip-membresias', null, '/servicios/vip-membresias.jpg', 0, 1, true),
  ((select id from c where slug='servicios-vip'), 'Gift Cards', 'servicios-vip-gift-cards', null, '/servicios/vip-gift-cards.jpg', 0, 2, true),
  ((select id from c where slug='servicios-vip'), 'Paquetes mensuales', 'servicios-vip-paquetes-mensuales', null, '/servicios/vip-paquetes-mensuales.jpg', 0, 3, true),
  ((select id from c where slug='servicios-vip'), 'Planes anuales', 'servicios-vip-planes-anuales', null, '/servicios/vip-planes-anuales.jpg', 0, 4, true),
  ((select id from c where slug='servicios-vip'), 'Concierge de belleza', 'servicios-vip-concierge-de-belleza', null, '/servicios/vip-concierge-belleza.jpg', 0, 5, true),
  ((select id from c where slug='servicios-vip'), 'Beauty Coach', 'servicios-vip-beauty-coach', null, null, 0, 6, true),
  ((select id from c where slug='servicios-vip'), 'Diagnóstico facial digital', 'servicios-vip-diagnostico-facial-digital', null, null, 0, 7, true),
  ((select id from c where slug='servicios-vip'), 'Diagnóstico corporal', 'servicios-vip-diagnostico-corporal', null, null, 0, 8, true),
  ((select id from c where slug='servicios-vip'), 'Seguimiento personalizado', 'servicios-vip-seguimiento-personalizado', null, null, 0, 9, true),
  ((select id from c where slug='servicios-vip'), 'Cabinas privadas VIP', 'servicios-vip-cabinas-privadas-vip', null, null, 0, 10, true),
  ((select id from c where slug='servicios-vip'), 'Servicio a domicilio', 'servicios-vip-servicio-a-domicilio', null, null, 0, 11, true),
  ((select id from c where slug='servicios-vip'), 'Atención para eventos', 'servicios-vip-atencion-para-eventos', null, null, 0, 12, true)
on conflict (slug) do update set categoria_id=excluded.categoria_id, nombre=excluded.nombre, grupo=excluded.grupo, imagen_url=excluded.imagen_url, orden=excluded.orden, activo=true;

-- Total: 20 areas, 272 servicios.
