-- ============================================================
-- Sync catálogo completo de Dálida Beauty & Spa a Supabase
-- Ejecutar en Supabase Studio > SQL Editor (o via psql)
-- Idempotente: puede ejecutarse múltiples veces sin duplicar.
-- ============================================================

-- 1) Columnas necesarias
alter table spanails.categorias add column if not exists icono text;
alter table spanails.servicios  add column if not exists grupo text;

-- 2) Categorías (áreas del catálogo)
insert into spanails.categorias (nombre, slug, descripcion, imagen_url, icono, orden, activo) values
  ('Estética Facial', 'estetica-facial', 'Limpiezas, hidratación, antiedad, manchas, acné y peelings.', '/servicios/limpieza-facial-basica.jpg', '✨', 100, true),
  ('Medicina Estética', 'medicina-estetica', 'Procedimientos realizados por profesional médico habilitado.', '/servicios/toxina-botulinica.jpg', '💉', 101, true),
  ('Tratamientos Corporales', 'tratamientos-corporales', 'Reductores, anticelulíticos, reafirmantes y modelado corporal.', '/servicios/criolipolisis.jpg', '🌿', 102, true),
  ('Depilación', 'depilacion', 'Depilación con cera, láser e hilo para rostro y cuerpo.', '/servicios/depilacion-facial.jpg', '🌸', 103, true),
  ('Masajes', 'masajes', 'Masajes relajantes, terapéuticos, drenaje y especializados.', '/servicios/masaje-sueco.jpg', '💆‍♀️', 104, true),
  ('Spa', 'spa', 'Circuito de spa y rituales de bienestar para una experiencia completa.', '/servicios/spa-sauna-seco.jpg', '🧖‍♀️', 105, true),
  ('Exfoliaciones', 'exfoliaciones', 'Exfoliaciones corporales con ingredientes naturales premium.', '/servicios/exfoliacion-sal-marina.jpg', '🧂', 106, true),
  ('Envolturas Corporales', 'envolturas-corporales', 'Envolturas nutritivas y detoxificantes para la piel.', '/servicios/envoltura-chocolate.jpg', '🍫', 107, true),
  ('Hidroterapia', 'hidroterapia', 'Terapias con agua, color y aromas para relajar cuerpo y mente.', '/servicios/hidroterapia-hidromasaje.jpg', '💧', 108, true),
  ('Manicura', 'manicura', 'Técnicas de manicura y decoraciones artísticas a medida.', '/servicios/manicura-tradicional.jpg', '💅', 109, true),
  ('Pedicura', 'pedicura', 'Pedicura estética, spa y podológica para pies sanos y prolijos.', '/servicios/pedicura-tradicional.jpg', '🦶', 110, true),
  ('Cejas', 'cejas', 'Diseño, perfilado y técnicas de pigmentación de cejas.', '/servicios/cejas-diseno.jpg', '👁️', 111, true),
  ('Pestañas', 'pestanas', 'Lifting, tinte y extensiones para una mirada intensa.', '/servicios/pestanas-lifting.jpg', '🦋', 112, true),
  ('Maquillaje', 'maquillaje', 'Maquillaje profesional para eventos, novias y producciones.', '/servicios/maquillaje-social.jpg', '💄', 113, true),
  ('Peluquería', 'peluqueria', 'Corte, color, tratamientos capilares y peinados de alta gama.', '/servicios/peluqueria-corte-mujer.jpg', '💇‍♀️', 114, true),
  ('Barbería', 'barberia', 'Corte y arreglo de barba con estilo y detalle masculino.', '/servicios/barberia-corte.jpg', '💈', 115, true),
  ('Bronceado', 'bronceado', 'Bronceado sin sol, uniforme y seguro para tu piel.', '/servicios/bronceado-spray-tan.jpg', '☀️', 116, true),
  ('Bienestar', 'bienestar', 'Terapias de relajación profunda para cuerpo y mente.', '/servicios/bienestar-aromaterapia.jpg', '🕯️', 117, true),
  ('Programas Premium', 'programas-premium', 'Experiencias completas de spa diseñadas para ocasiones especiales.', '/servicios/programa-spa-parejas.jpg', '👑', 118, true),
  ('Servicios VIP', 'servicios-vip', 'Membresías, atención exclusiva y beneficios pensados para vos.', '/servicios/vip-membresias.jpg', '⭐', 119, true)
on conflict (slug) do update set
  nombre = excluded.nombre,
  descripcion = excluded.descripcion,
  imagen_url = coalesce(spanails.categorias.imagen_url, excluded.imagen_url),
  icono = excluded.icono,
  activo = true;

-- 3) Servicios
with c as (select id, slug from spanails.categorias)
insert into spanails.servicios (categoria_id, nombre, slug, descripcion, duracion_min, precio, imagen_url, grupo, orden, activo) values
  ((select id from c where slug='estetica-facial'), 'Limpieza facial básica', 'estetica-facial-limpieza-facial-basica', null, null, 0, '/servicios/limpieza-facial-basica.jpg', 'Limpiezas faciales', 0, true),
  ((select id from c where slug='estetica-facial'), 'Limpieza facial profunda', 'estetica-facial-limpieza-facial-profunda', null, null, 0, '/servicios/limpieza-facial-profunda.jpg', 'Limpiezas faciales', 1, true),
  ((select id from c where slug='estetica-facial'), 'Limpieza ultrasónica', 'estetica-facial-limpieza-ultrasonica', null, null, 0, '/servicios/limpieza-ultrasonica.jpg', 'Limpiezas faciales', 2, true),
  ((select id from c where slug='estetica-facial'), 'Limpieza con punta de diamante', 'estetica-facial-limpieza-con-punta-de-diamante', null, null, 0, '/servicios/limpieza-punta-diamante.jpg', 'Limpiezas faciales', 3, true),
  ((select id from c where slug='estetica-facial'), 'Limpieza con espátula ultrasónica', 'estetica-facial-limpieza-con-espatula-ultrasonica', null, null, 0, '/servicios/limpieza-espatula-ultrasonica.jpg', 'Limpiezas faciales', 4, true),
  ((select id from c where slug='estetica-facial'), 'Higiene facial para piel grasa', 'estetica-facial-higiene-facial-para-piel-grasa', null, null, 0, '/servicios/higiene-facial-piel-grasa.jpg', 'Limpiezas faciales', 5, true),
  ((select id from c where slug='estetica-facial'), 'Higiene facial para piel seca', 'estetica-facial-higiene-facial-para-piel-seca', null, null, 0, '/servicios/higiene-facial-piel-seca.jpg', 'Limpiezas faciales', 6, true),
  ((select id from c where slug='estetica-facial'), 'Higiene facial para piel sensible', 'estetica-facial-higiene-facial-para-piel-sensible', null, null, 0, '/servicios/higiene-facial-piel-sensible.jpg', 'Limpiezas faciales', 7, true),
  ((select id from c where slug='estetica-facial'), 'Higiene facial masculina', 'estetica-facial-higiene-facial-masculina', null, null, 0, '/servicios/higiene-facial-masculina.jpg', 'Limpiezas faciales', 8, true),
  ((select id from c where slug='estetica-facial'), 'Limpieza para adolescentes', 'estetica-facial-limpieza-para-adolescentes', null, null, 0, '/servicios/limpieza-adolescentes.jpg', 'Limpiezas faciales', 9, true),
  ((select id from c where slug='estetica-facial'), 'Hidratación profunda', 'estetica-facial-hidratacion-profunda', null, null, 0, '/servicios/hidratacion-profunda.jpg', 'Tratamientos hidratantes', 10, true),
  ((select id from c where slug='estetica-facial'), 'Nutrición facial', 'estetica-facial-nutricion-facial', null, null, 0, '/servicios/nutricion-facial.jpg', 'Tratamientos hidratantes', 11, true),
  ((select id from c where slug='estetica-facial'), 'Oxigenoterapia', 'estetica-facial-oxigenoterapia', null, null, 0, '/servicios/oxigenoterapia.jpg', 'Tratamientos hidratantes', 12, true),
  ((select id from c where slug='estetica-facial'), 'Tratamiento calmante', 'estetica-facial-tratamiento-calmante', null, null, 0, '/servicios/tratamiento-calmante.jpg', 'Tratamientos hidratantes', 13, true),
  ((select id from c where slug='estetica-facial'), 'Tratamiento reparador', 'estetica-facial-tratamiento-reparador', null, null, 0, '/servicios/tratamiento-reparador.jpg', 'Tratamientos hidratantes', 14, true),
  ((select id from c where slug='estetica-facial'), 'Mascarillas profesionales', 'estetica-facial-mascarillas-profesionales', null, null, 0, '/servicios/mascarillas-profesionales.jpg', 'Tratamientos hidratantes', 15, true),
  ((select id from c where slug='estetica-facial'), 'Rejuvenecimiento facial', 'estetica-facial-rejuvenecimiento-facial', null, null, 0, '/servicios/rejuvenecimiento-facial.jpg', 'Antiedad', 16, true),
  ((select id from c where slug='estetica-facial'), 'Lifting facial sin cirugía', 'estetica-facial-lifting-facial-sin-cirugia', null, null, 0, '/servicios/lifting-facial-sin-cirugia.jpg', 'Antiedad', 17, true),
  ((select id from c where slug='estetica-facial'), 'Radiofrecuencia facial', 'estetica-facial-radiofrecuencia-facial', null, null, 0, '/servicios/radiofrecuencia-facial.jpg', 'Antiedad', 18, true),
  ((select id from c where slug='estetica-facial'), 'HIFU', 'estetica-facial-hifu', null, null, 0, '/servicios/hifu.jpg', 'Antiedad', 19, true),
  ((select id from c where slug='estetica-facial'), 'Microneedling (Dermapen)', 'estetica-facial-microneedling-dermapen', null, null, 0, '/servicios/microneedling-dermapen.jpg', 'Antiedad', 20, true),
  ((select id from c where slug='estetica-facial'), 'Mesoterapia virtual', 'estetica-facial-mesoterapia-virtual', null, null, 0, '/servicios/mesoterapia-virtual.jpg', 'Antiedad', 21, true),
  ((select id from c where slug='estetica-facial'), 'Electroporación', 'estetica-facial-electroporacion', null, null, 0, '/servicios/electroporacion.jpg', 'Antiedad', 22, true),
  ((select id from c where slug='estetica-facial'), 'Colágeno facial', 'estetica-facial-colageno-facial', null, null, 0, '/servicios/colageno-facial.jpg', 'Antiedad', 23, true),
  ((select id from c where slug='estetica-facial'), 'Elastina', 'estetica-facial-elastina', null, null, 0, '/servicios/elastina.jpg', 'Antiedad', 24, true),
  ((select id from c where slug='estetica-facial'), 'Fototerapia LED', 'estetica-facial-fototerapia-led', null, null, 0, '/servicios/fototerapia-led.jpg', 'Antiedad', 25, true),
  ((select id from c where slug='estetica-facial'), 'Terapia con oxígeno', 'estetica-facial-terapia-con-oxigeno', null, null, 0, '/servicios/terapia-con-oxigeno.jpg', 'Antiedad', 26, true),
  ((select id from c where slug='estetica-facial'), 'Tratamiento despigmentante', 'estetica-facial-tratamiento-despigmentante', null, null, 0, '/servicios/tratamiento-despigmentante.jpg', 'Manchas', 27, true),
  ((select id from c where slug='estetica-facial'), 'Melasma', 'estetica-facial-melasma', null, null, 0, '/servicios/melasma.jpg', 'Manchas', 28, true),
  ((select id from c where slug='estetica-facial'), 'Manchas solares', 'estetica-facial-manchas-solares', null, null, 0, '/servicios/manchas-solares.jpg', 'Manchas', 29, true),
  ((select id from c where slug='estetica-facial'), 'Manchas postacné', 'estetica-facial-manchas-postacne', null, null, 0, '/servicios/manchas-postacne.jpg', 'Manchas', 30, true),
  ((select id from c where slug='estetica-facial'), 'Peelings despigmentantes', 'estetica-facial-peelings-despigmentantes', null, null, 0, '/servicios/peelings-despigmentantes.jpg', 'Manchas', 31, true),
  ((select id from c where slug='estetica-facial'), 'Tratamiento antiacné', 'estetica-facial-tratamiento-antiacne', null, null, 0, '/servicios/tratamiento-antiacne.jpg', 'Acné', 32, true),
  ((select id from c where slug='estetica-facial'), 'Control de sebo', 'estetica-facial-control-de-sebo', null, null, 0, '/servicios/control-de-sebo.jpg', 'Acné', 33, true),
  ((select id from c where slug='estetica-facial'), 'Reducción de poros', 'estetica-facial-reduccion-de-poros', null, null, 0, '/servicios/reduccion-de-poros.jpg', 'Acné', 34, true),
  ((select id from c where slug='estetica-facial'), 'Tratamiento para cicatrices', 'estetica-facial-tratamiento-para-cicatrices', null, null, 0, '/servicios/tratamiento-para-cicatrices.jpg', 'Acné', 35, true),
  ((select id from c where slug='estetica-facial'), 'Químicos', 'estetica-facial-quimicos', null, null, 0, '/servicios/peeling-quimicos.jpg', 'Peelings', 36, true),
  ((select id from c where slug='estetica-facial'), 'Enzimáticos', 'estetica-facial-enzimaticos', null, null, 0, '/servicios/peeling-enzimaticos.jpg', 'Peelings', 37, true),
  ((select id from c where slug='estetica-facial'), 'Diamante', 'estetica-facial-diamante', null, null, 0, '/servicios/peeling-diamante.jpg', 'Peelings', 38, true),
  ((select id from c where slug='estetica-facial'), 'Carbón activado', 'estetica-facial-carbon-activado', null, null, 0, '/servicios/peeling-carbon-activado.jpg', 'Peelings', 39, true),
  ((select id from c where slug='estetica-facial'), 'Hollywood Peel', 'estetica-facial-hollywood-peel', null, null, 0, '/servicios/peeling-hollywood.jpg', 'Peelings', 40, true),
  ((select id from c where slug='medicina-estetica'), 'Toxina botulínica', 'medicina-estetica-toxina-botulinica', null, null, 0, '/servicios/toxina-botulinica.jpg', null, 0, true),
  ((select id from c where slug='medicina-estetica'), 'Ácido hialurónico', 'medicina-estetica-acido-hialuronico', null, null, 0, '/servicios/acido-hialuronico.jpg', null, 1, true),
  ((select id from c where slug='medicina-estetica'), 'Bioestimuladores', 'medicina-estetica-bioestimuladores', null, null, 0, '/servicios/bioestimuladores.jpg', null, 2, true),
  ((select id from c where slug='medicina-estetica'), 'Plasma Rico en Plaquetas', 'medicina-estetica-plasma-rico-en-plaquetas', null, null, 0, '/servicios/plasma-rico-plaquetas.jpg', null, 3, true),
  ((select id from c where slug='medicina-estetica'), 'Mesoterapia', 'medicina-estetica-mesoterapia', null, null, 0, '/servicios/mesoterapia.jpg', null, 4, true),
  ((select id from c where slug='medicina-estetica'), 'Hilos tensores', 'medicina-estetica-hilos-tensores', null, null, 0, '/servicios/hilos-tensores.jpg', null, 5, true),
  ((select id from c where slug='medicina-estetica'), 'Relleno de labios', 'medicina-estetica-relleno-de-labios', null, null, 0, '/servicios/relleno-labios.jpg', null, 6, true),
  ((select id from c where slug='medicina-estetica'), 'Perfilado mandibular', 'medicina-estetica-perfilado-mandibular', null, null, 0, '/servicios/perfilado-mandibular.jpg', null, 7, true),
  ((select id from c where slug='medicina-estetica'), 'Rinomodelación', 'medicina-estetica-rinomodelacion', null, null, 0, '/servicios/rinomodelacion.jpg', null, 8, true),
  ((select id from c where slug='medicina-estetica'), 'Biorrevitalización', 'medicina-estetica-biorrevitalizacion', null, null, 0, '/servicios/biorrevitalizacion.jpg', null, 9, true),
  ((select id from c where slug='tratamientos-corporales'), 'Criolipólisis', 'tratamientos-corporales-criolipolisis', null, null, 0, '/servicios/criolipolisis.jpg', 'Reductores', 0, true),
  ((select id from c where slug='tratamientos-corporales'), 'Cavitación', 'tratamientos-corporales-cavitacion', null, null, 0, '/servicios/cavitacion.jpg', 'Reductores', 1, true),
  ((select id from c where slug='tratamientos-corporales'), 'Lipoláser', 'tratamientos-corporales-lipolaser', null, null, 0, '/servicios/lipolaser.jpg', 'Reductores', 2, true),
  ((select id from c where slug='tratamientos-corporales'), 'Radiofrecuencia corporal', 'tratamientos-corporales-radiofrecuencia-corporal', null, null, 0, '/servicios/radiofrecuencia-corporal.jpg', 'Reductores', 3, true),
  ((select id from c where slug='tratamientos-corporales'), 'Ultrasonido', 'tratamientos-corporales-ultrasonido', null, null, 0, '/servicios/ultrasonido.jpg', 'Reductores', 4, true),
  ((select id from c where slug='tratamientos-corporales'), 'EMS Sculpt', 'tratamientos-corporales-ems-sculpt', null, null, 0, '/servicios/ems-sculpt.jpg', 'Reductores', 5, true),
  ((select id from c where slug='tratamientos-corporales'), 'Vacumterapia', 'tratamientos-corporales-vacumterapia', null, null, 0, '/servicios/vacumterapia.jpg', 'Reductores', 6, true),
  ((select id from c where slug='tratamientos-corporales'), 'Ondas rusas', 'tratamientos-corporales-ondas-rusas', null, null, 0, '/servicios/ondas-rusas.jpg', 'Reductores', 7, true),
  ((select id from c where slug='tratamientos-corporales'), 'Drenaje', 'tratamientos-corporales-drenaje', null, null, 0, '/servicios/drenaje.jpg', 'Celulitis', 8, true),
  ((select id from c where slug='tratamientos-corporales'), 'Maderoterapia', 'tratamientos-corporales-maderoterapia', null, null, 0, '/servicios/maderoterapia.jpg', 'Celulitis', 9, true),
  ((select id from c where slug='tratamientos-corporales'), 'Endermoterapia', 'tratamientos-corporales-endermoterapia', null, null, 0, '/servicios/endermoterapia.jpg', 'Celulitis', 10, true),
  ((select id from c where slug='tratamientos-corporales'), 'Presoterapia', 'tratamientos-corporales-presoterapia', null, null, 0, '/servicios/presoterapia.jpg', 'Celulitis', 11, true),
  ((select id from c where slug='tratamientos-corporales'), 'Anticelulítico intensivo', 'tratamientos-corporales-anticelulitico-intensivo', null, null, 0, '/servicios/anticelulitico-intensivo.jpg', 'Celulitis', 12, true),
  ((select id from c where slug='tratamientos-corporales'), 'Radiofrecuencia', 'tratamientos-corporales-radiofrecuencia', null, null, 0, '/servicios/flacidez-radiofrecuencia.jpg', 'Flacidez', 13, true),
  ((select id from c where slug='tratamientos-corporales'), 'HIFU corporal', 'tratamientos-corporales-hifu-corporal', null, null, 0, '/servicios/hifu-corporal.jpg', 'Flacidez', 14, true),
  ((select id from c where slug='tratamientos-corporales'), 'Electroestimulación', 'tratamientos-corporales-electroestimulacion', null, null, 0, '/servicios/electroestimulacion.jpg', 'Flacidez', 15, true),
  ((select id from c where slug='tratamientos-corporales'), 'Colágeno corporal', 'tratamientos-corporales-colageno-corporal', null, null, 0, '/servicios/colageno-corporal.jpg', 'Flacidez', 16, true),
  ((select id from c where slug='tratamientos-corporales'), 'Microneedling', 'tratamientos-corporales-microneedling', null, null, 0, '/servicios/microneedling-corporal.jpg', 'Estrías', 17, true),
  ((select id from c where slug='tratamientos-corporales'), 'Plasma', 'tratamientos-corporales-plasma', null, null, 0, '/servicios/plasma-corporal.jpg', 'Estrías', 18, true),
  ((select id from c where slug='tratamientos-corporales'), 'Láser', 'tratamientos-corporales-laser', null, null, 0, '/servicios/laser-corporal.jpg', 'Estrías', 19, true),
  ((select id from c where slug='tratamientos-corporales'), 'Peelings', 'tratamientos-corporales-peelings', null, null, 0, '/servicios/peelings-corporal.jpg', 'Estrías', 20, true),
  ((select id from c where slug='tratamientos-corporales'), 'Remodelación', 'tratamientos-corporales-remodelacion', null, null, 0, '/servicios/remodelacion.jpg', 'Modelado corporal', 21, true),
  ((select id from c where slug='tratamientos-corporales'), 'Tonificación', 'tratamientos-corporales-tonificacion', null, null, 0, '/servicios/tonificacion.jpg', 'Modelado corporal', 22, true),
  ((select id from c where slug='tratamientos-corporales'), 'Esculpido corporal', 'tratamientos-corporales-esculpido-corporal', null, null, 0, '/servicios/esculpido-corporal.jpg', 'Modelado corporal', 23, true),
  ((select id from c where slug='tratamientos-corporales'), 'Levantamiento de glúteos', 'tratamientos-corporales-levantamiento-de-gluteos', null, null, 0, '/servicios/levantamiento-gluteos.jpg', 'Modelado corporal', 24, true),
  ((select id from c where slug='depilacion'), 'Facial', 'depilacion-facial', null, null, 0, '/servicios/depilacion-facial.jpg', 'Cera', 0, true),
  ((select id from c where slug='depilacion'), 'Axilas', 'depilacion-axilas', null, null, 0, '/servicios/depilacion-axilas.jpg', 'Cera', 1, true),
  ((select id from c where slug='depilacion'), 'Brazos', 'depilacion-brazos', null, null, 0, '/servicios/depilacion-brazos.jpg', 'Cera', 2, true),
  ((select id from c where slug='depilacion'), 'Piernas', 'depilacion-piernas', null, null, 0, '/servicios/depilacion-piernas.jpg', 'Cera', 3, true),
  ((select id from c where slug='depilacion'), 'Espalda', 'depilacion-espalda', null, null, 0, '/servicios/depilacion-espalda.jpg', 'Cera', 4, true),
  ((select id from c where slug='depilacion'), 'Abdomen', 'depilacion-abdomen', null, null, 0, '/servicios/depilacion-abdomen.jpg', 'Cera', 5, true),
  ((select id from c where slug='depilacion'), 'Bikini', 'depilacion-bikini', null, null, 0, '/servicios/depilacion-bikini.jpg', 'Cera', 6, true),
  ((select id from c where slug='depilacion'), 'Brasileña', 'depilacion-brasilena', null, null, 0, '/servicios/depilacion-brasilena.jpg', 'Cera', 7, true),
  ((select id from c where slug='depilacion'), 'Íntima', 'depilacion-intima', null, null, 0, '/servicios/depilacion-intima.jpg', 'Cera', 8, true),
  ((select id from c where slug='depilacion'), 'Diodo', 'depilacion-diodo', null, null, 0, '/servicios/depilacion-diodo.jpg', 'Láser', 9, true),
  ((select id from c where slug='depilacion'), 'Alexandrita', 'depilacion-alexandrita', null, null, 0, '/servicios/depilacion-alexandrita.jpg', 'Láser', 10, true),
  ((select id from c where slug='depilacion'), 'IPL', 'depilacion-ipl', null, null, 0, '/servicios/depilacion-ipl.jpg', 'Láser', 11, true),
  ((select id from c where slug='depilacion'), 'Cejas', 'depilacion-cejas', null, null, 0, '/servicios/depilacion-hilo-cejas.jpg', 'Hilo', 12, true),
  ((select id from c where slug='depilacion'), 'Rostro', 'depilacion-rostro', null, null, 0, '/servicios/depilacion-hilo-rostro.jpg', 'Hilo', 13, true),
  ((select id from c where slug='depilacion'), 'Labio', 'depilacion-labio', null, null, 0, '/servicios/depilacion-hilo-labio.jpg', 'Hilo', 14, true),
  ((select id from c where slug='masajes'), 'Sueco', 'masajes-sueco', null, null, 0, '/servicios/masaje-sueco.jpg', 'Relajantes', 0, true),
  ((select id from c where slug='masajes'), 'Aromaterapia', 'masajes-aromaterapia', null, null, 0, '/servicios/masaje-aromaterapia.jpg', 'Relajantes', 1, true),
  ((select id from c where slug='masajes'), 'Piedras calientes', 'masajes-piedras-calientes', null, null, 0, '/servicios/masaje-piedras-calientes.jpg', 'Relajantes', 2, true),
  ((select id from c where slug='masajes'), 'Velas', 'masajes-velas', null, null, 0, '/servicios/masaje-velas.jpg', 'Relajantes', 3, true),
  ((select id from c where slug='masajes'), 'Bambuterapia', 'masajes-bambuterapia', null, null, 0, '/servicios/masaje-bambuterapia.jpg', 'Relajantes', 4, true),
  ((select id from c where slug='masajes'), 'Descontracturante', 'masajes-descontracturante', null, null, 0, '/servicios/masaje-descontracturante.jpg', 'Terapéuticos', 5, true),
  ((select id from c where slug='masajes'), 'Deportivo', 'masajes-deportivo', null, null, 0, '/servicios/masaje-deportivo.jpg', 'Terapéuticos', 6, true),
  ((select id from c where slug='masajes'), 'Cervical', 'masajes-cervical', null, null, 0, '/servicios/masaje-cervical.jpg', 'Terapéuticos', 7, true),
  ((select id from c where slug='masajes'), 'Lumbar', 'masajes-lumbar', null, null, 0, '/servicios/masaje-lumbar.jpg', 'Terapéuticos', 8, true),
  ((select id from c where slug='masajes'), 'Espalda completa', 'masajes-espalda-completa', null, null, 0, '/servicios/masaje-espalda-completa.jpg', 'Terapéuticos', 9, true),
  ((select id from c where slug='masajes'), 'Manual', 'masajes-manual', null, null, 0, '/servicios/masaje-manual.jpg', 'Drenaje', 10, true),
  ((select id from c where slug='masajes'), 'Linfático', 'masajes-linfatico', null, null, 0, '/servicios/masaje-linfatico.jpg', 'Drenaje', 11, true),
  ((select id from c where slug='masajes'), 'Postoperatorio', 'masajes-postoperatorio', null, null, 0, '/servicios/masaje-postoperatorio.jpg', 'Drenaje', 12, true),
  ((select id from c where slug='masajes'), 'Prenatal', 'masajes-prenatal', null, null, 0, '/servicios/masaje-prenatal.jpg', 'Especializados', 13, true),
  ((select id from c where slug='masajes'), 'Posparto', 'masajes-posparto', null, null, 0, '/servicios/masaje-posparto.jpg', 'Especializados', 14, true),
  ((select id from c where slug='masajes'), 'Reflexología', 'masajes-reflexologia', null, null, 0, '/servicios/masaje-reflexologia.jpg', 'Especializados', 15, true),
  ((select id from c where slug='masajes'), 'Craneofacial', 'masajes-craneofacial', null, null, 0, '/servicios/masaje-craneofacial.jpg', 'Especializados', 16, true),
  ((select id from c where slug='spa'), 'Sauna seco', 'spa-sauna-seco', null, null, 0, '/servicios/spa-sauna-seco.jpg', 'Circuito Spa', 0, true),
  ((select id from c where slug='spa'), 'Sauna húmedo', 'spa-sauna-humedo', null, null, 0, '/servicios/spa-sauna-humedo.jpg', 'Circuito Spa', 1, true),
  ((select id from c where slug='spa'), 'Baño turco', 'spa-bano-turco', null, null, 0, '/servicios/spa-bano-turco.jpg', 'Circuito Spa', 2, true),
  ((select id from c where slug='spa'), 'Jacuzzi', 'spa-jacuzzi', null, null, 0, '/servicios/spa-jacuzzi.jpg', 'Circuito Spa', 3, true),
  ((select id from c where slug='spa'), 'Hidromasaje', 'spa-hidromasaje', null, null, 0, '/servicios/spa-hidromasaje.jpg', 'Circuito Spa', 4, true),
  ((select id from c where slug='spa'), 'Piscina climatizada', 'spa-piscina-climatizada', null, null, 0, '/servicios/spa-piscina-climatizada.jpg', 'Circuito Spa', 5, true),
  ((select id from c where slug='spa'), 'Duchas sensoriales', 'spa-duchas-sensoriales', null, null, 0, '/servicios/spa-duchas-sensoriales.jpg', 'Circuito Spa', 6, true),
  ((select id from c where slug='spa'), 'Sala de relajación', 'spa-sala-de-relajacion', null, null, 0, '/servicios/spa-sala-relajacion.jpg', 'Circuito Spa', 7, true),
  ((select id from c where slug='spa'), 'Ritual relajante', 'spa-ritual-relajante', null, null, 0, '/servicios/spa-ritual-relajante.jpg', 'Rituales Spa', 8, true),
  ((select id from c where slug='spa'), 'Ritual romántico', 'spa-ritual-romantico', null, null, 0, '/servicios/spa-ritual-romantico.jpg', 'Rituales Spa', 9, true),
  ((select id from c where slug='spa'), 'Ritual para parejas', 'spa-ritual-para-parejas', null, null, 0, '/servicios/spa-ritual-parejas.jpg', 'Rituales Spa', 10, true),
  ((select id from c where slug='spa'), 'Ritual antiestrés', 'spa-ritual-antiestres', null, null, 0, '/servicios/spa-ritual-antiestres.jpg', 'Rituales Spa', 11, true),
  ((select id from c where slug='spa'), 'Ritual detox', 'spa-ritual-detox', null, null, 0, '/servicios/spa-ritual-detox.jpg', 'Rituales Spa', 12, true),
  ((select id from c where slug='spa'), 'Ritual premium', 'spa-ritual-premium', null, null, 0, '/servicios/spa-ritual-premium.jpg', 'Rituales Spa', 13, true),
  ((select id from c where slug='spa'), 'Ritual ejecutivo', 'spa-ritual-ejecutivo', null, null, 0, '/servicios/spa-ritual-ejecutivo.jpg', 'Rituales Spa', 14, true),
  ((select id from c where slug='spa'), 'Ritual bridal', 'spa-ritual-bridal', null, null, 0, '/servicios/spa-ritual-bridal.jpg', 'Rituales Spa', 15, true),
  ((select id from c where slug='exfoliaciones'), 'Sal marina', 'exfoliaciones-sal-marina', null, null, 0, '/servicios/exfoliacion-sal-marina.jpg', null, 0, true),
  ((select id from c where slug='exfoliaciones'), 'Azúcar', 'exfoliaciones-azucar', null, null, 0, '/servicios/exfoliacion-azucar.jpg', null, 1, true),
  ((select id from c where slug='exfoliaciones'), 'Café', 'exfoliaciones-cafe', null, null, 0, '/servicios/exfoliacion-cafe.jpg', null, 2, true),
  ((select id from c where slug='exfoliaciones'), 'Chocolate', 'exfoliaciones-chocolate', null, null, 0, '/servicios/exfoliacion-chocolate.jpg', null, 3, true),
  ((select id from c where slug='exfoliaciones'), 'Coco', 'exfoliaciones-coco', null, null, 0, '/servicios/exfoliacion-coco.jpg', null, 4, true),
  ((select id from c where slug='exfoliaciones'), 'Vino', 'exfoliaciones-vino', null, null, 0, '/servicios/exfoliacion-vino.jpg', null, 5, true),
  ((select id from c where slug='exfoliaciones'), 'Oro', 'exfoliaciones-oro', null, null, 0, '/servicios/exfoliacion-oro.jpg', null, 6, true),
  ((select id from c where slug='exfoliaciones'), 'Perlas', 'exfoliaciones-perlas', null, null, 0, '/servicios/exfoliacion-perlas.jpg', null, 7, true),
  ((select id from c where slug='exfoliaciones'), 'Sales del Himalaya', 'exfoliaciones-sales-del-himalaya', null, null, 0, '/servicios/exfoliacion-sales-himalaya.jpg', null, 8, true),
  ((select id from c where slug='envolturas-corporales'), 'Chocolate', 'envolturas-corporales-chocolate', null, null, 0, '/servicios/envoltura-chocolate.jpg', null, 0, true),
  ((select id from c where slug='envolturas-corporales'), 'Algas', 'envolturas-corporales-algas', null, null, 0, '/servicios/envoltura-algas.jpg', null, 1, true),
  ((select id from c where slug='envolturas-corporales'), 'Fango', 'envolturas-corporales-fango', null, null, 0, '/servicios/envoltura-fango.jpg', null, 2, true),
  ((select id from c where slug='envolturas-corporales'), 'Barro volcánico', 'envolturas-corporales-barro-volcanico', null, null, 0, '/servicios/envoltura-barro-volcanico.jpg', null, 3, true),
  ((select id from c where slug='envolturas-corporales'), 'Arcillas', 'envolturas-corporales-arcillas', null, null, 0, '/servicios/envoltura-arcillas.jpg', null, 4, true),
  ((select id from c where slug='envolturas-corporales'), 'Vino', 'envolturas-corporales-vino', null, null, 0, '/servicios/envoltura-vino.jpg', null, 5, true),
  ((select id from c where slug='envolturas-corporales'), 'Oro', 'envolturas-corporales-oro', null, null, 0, '/servicios/envoltura-oro.jpg', null, 6, true),
  ((select id from c where slug='envolturas-corporales'), 'Café', 'envolturas-corporales-cafe', null, null, 0, '/servicios/envoltura-cafe.jpg', null, 7, true),
  ((select id from c where slug='envolturas-corporales'), 'Aloe vera', 'envolturas-corporales-aloe-vera', null, null, 0, '/servicios/envoltura-aloe-vera.jpg', null, 8, true),
  ((select id from c where slug='hidroterapia'), 'Hidromasaje', 'hidroterapia-hidromasaje', null, null, 0, '/servicios/hidroterapia-hidromasaje.jpg', null, 0, true),
  ((select id from c where slug='hidroterapia'), 'Cromoterapia', 'hidroterapia-cromoterapia', null, null, 0, '/servicios/hidroterapia-cromoterapia.jpg', null, 1, true),
  ((select id from c where slug='hidroterapia'), 'Aromaterapia', 'hidroterapia-aromaterapia', null, null, 0, '/servicios/hidroterapia-aromaterapia.jpg', null, 2, true),
  ((select id from c where slug='hidroterapia'), 'Baños minerales', 'hidroterapia-banos-minerales', null, null, 0, '/servicios/hidroterapia-banos-minerales.jpg', null, 3, true),
  ((select id from c where slug='hidroterapia'), 'Baños de leche', 'hidroterapia-banos-de-leche', null, null, 0, '/servicios/hidroterapia-banos-leche.jpg', null, 4, true),
  ((select id from c where slug='hidroterapia'), 'Sales aromáticas', 'hidroterapia-sales-aromaticas', null, null, 0, '/servicios/hidroterapia-sales-aromaticas.jpg', null, 5, true),
  ((select id from c where slug='manicura'), 'Tradicional', 'manicura-tradicional', null, null, 0, '/servicios/manicura-tradicional.jpg', 'Técnicas', 0, true),
  ((select id from c where slug='manicura'), 'Spa', 'manicura-spa', null, null, 0, '/servicios/manicura-spa.jpg', 'Técnicas', 1, true),
  ((select id from c where slug='manicura'), 'Francesa', 'manicura-francesa', null, null, 0, '/servicios/manicura-francesa.jpg', 'Técnicas', 2, true),
  ((select id from c where slug='manicura'), 'Semipermanente', 'manicura-semipermanente', null, null, 0, '/servicios/manicura-semipermanente.jpg', 'Técnicas', 3, true),
  ((select id from c where slug='manicura'), 'Gel', 'manicura-gel', null, null, 0, '/servicios/manicura-gel.jpg', 'Técnicas', 4, true),
  ((select id from c where slug='manicura'), 'Polygel', 'manicura-polygel', null, null, 0, '/servicios/manicura-polygel.jpg', 'Técnicas', 5, true),
  ((select id from c where slug='manicura'), 'Acrílicas', 'manicura-acrilicas', null, null, 0, '/servicios/manicura-acrilicas.jpg', 'Técnicas', 6, true),
  ((select id from c where slug='manicura'), 'Soft Gel', 'manicura-soft-gel', null, null, 0, '/servicios/manicura-soft-gel.jpg', 'Técnicas', 7, true),
  ((select id from c where slug='manicura'), 'Rubber Base', 'manicura-rubber-base', null, null, 0, '/servicios/manicura-rubber-base.jpg', 'Técnicas', 8, true),
  ((select id from c where slug='manicura'), 'Press On', 'manicura-press-on', null, null, 0, '/servicios/manicura-press-on.jpg', 'Técnicas', 9, true),
  ((select id from c where slug='manicura'), 'Kapping', 'manicura-kapping', null, null, 0, '/servicios/manicura-kapping.jpg', 'Técnicas', 10, true),
  ((select id from c where slug='manicura'), 'Esculpidas', 'manicura-esculpidas', null, null, 0, '/servicios/manicura-esculpidas.jpg', 'Técnicas', 11, true),
  ((select id from c where slug='manicura'), 'Nail Art', 'manicura-nail-art', null, null, 0, '/servicios/manicura-nail-art.jpg', 'Decoraciones', 12, true),
  ((select id from c where slug='manicura'), 'Cristales Swarovski', 'manicura-cristales-swarovski', null, null, 0, '/servicios/manicura-cristales-swarovski.jpg', 'Decoraciones', 13, true),
  ((select id from c where slug='manicura'), 'Efecto espejo', 'manicura-efecto-espejo', null, null, 0, '/servicios/manicura-efecto-espejo.jpg', 'Decoraciones', 14, true),
  ((select id from c where slug='manicura'), 'Baby Boomer', 'manicura-baby-boomer', null, null, 0, '/servicios/manicura-baby-boomer.jpg', 'Decoraciones', 15, true),
  ((select id from c where slug='manicura'), 'Ojo de gato', 'manicura-ojo-de-gato', null, null, 0, '/servicios/manicura-ojo-de-gato.jpg', 'Decoraciones', 16, true),
  ((select id from c where slug='manicura'), 'Encapsulados', 'manicura-encapsulados', null, null, 0, '/servicios/manicura-encapsulados.jpg', 'Decoraciones', 17, true),
  ((select id from c where slug='manicura'), 'Foil', 'manicura-foil', null, null, 0, '/servicios/manicura-foil.jpg', 'Decoraciones', 18, true),
  ((select id from c where slug='manicura'), 'Acuarela', 'manicura-acuarela', null, null, 0, '/servicios/manicura-acuarela.jpg', 'Decoraciones', 19, true),
  ((select id from c where slug='manicura'), '3D', 'manicura-3d', null, null, 0, '/servicios/manicura-3d.jpg', 'Decoraciones', 20, true),
  ((select id from c where slug='pedicura'), 'Tradicional', 'pedicura-tradicional', null, null, 0, '/servicios/pedicura-tradicional.jpg', null, 0, true),
  ((select id from c where slug='pedicura'), 'Spa', 'pedicura-spa', null, null, 0, '/servicios/pedicura-spa.jpg', null, 1, true),
  ((select id from c where slug='pedicura'), 'Podológica', 'pedicura-podologica', null, null, 0, '/servicios/pedicura-podologica.jpg', null, 2, true),
  ((select id from c where slug='pedicura'), 'Semipermanente', 'pedicura-semipermanente', null, null, 0, '/servicios/pedicura-semipermanente.jpg', null, 3, true),
  ((select id from c where slug='pedicura'), 'Gel', 'pedicura-gel', null, null, 0, '/servicios/pedicura-gel.jpg', null, 4, true),
  ((select id from c where slug='pedicura'), 'Callosidades', 'pedicura-callosidades', null, null, 0, '/servicios/pedicura-callosidades.jpg', null, 5, true),
  ((select id from c where slug='pedicura'), 'Talones agrietados', 'pedicura-talones-agrietados', null, null, 0, '/servicios/pedicura-talones-agrietados.jpg', null, 6, true),
  ((select id from c where slug='pedicura'), 'Parafina', 'pedicura-parafina', null, null, 0, '/servicios/pedicura-parafina.jpg', null, 7, true),
  ((select id from c where slug='pedicura'), 'Reflexología podal', 'pedicura-reflexologia-podal', null, null, 0, '/servicios/pedicura-reflexologia-podal.jpg', null, 8, true),
  ((select id from c where slug='cejas'), 'Diseño', 'cejas-diseno', null, null, 0, '/servicios/cejas-diseno.jpg', null, 0, true),
  ((select id from c where slug='cejas'), 'Perfilado', 'cejas-perfilado', null, null, 0, '/servicios/cejas-perfilado.jpg', null, 1, true),
  ((select id from c where slug='cejas'), 'Depilación', 'cejas-depilacion', null, null, 0, '/servicios/cejas-depilacion.jpg', null, 2, true),
  ((select id from c where slug='cejas'), 'Hilo', 'cejas-hilo', null, null, 0, '/servicios/cejas-hilo.jpg', null, 3, true),
  ((select id from c where slug='cejas'), 'Pinza', 'cejas-pinza', null, null, 0, '/servicios/cejas-pinza.jpg', null, 4, true),
  ((select id from c where slug='cejas'), 'Henna', 'cejas-henna', null, null, 0, '/servicios/cejas-henna.jpg', null, 5, true),
  ((select id from c where slug='cejas'), 'Laminado', 'cejas-laminado', null, null, 0, '/servicios/cejas-laminado.jpg', null, 6, true),
  ((select id from c where slug='cejas'), 'Microblading', 'cejas-microblading', null, null, 0, '/servicios/cejas-microblading.jpg', null, 7, true),
  ((select id from c where slug='cejas'), 'Micropigmentación', 'cejas-micropigmentacion', null, null, 0, '/servicios/cejas-micropigmentacion.jpg', null, 8, true),
  ((select id from c where slug='cejas'), 'Powder Brows', 'cejas-powder-brows', null, null, 0, '/servicios/cejas-powder-brows.jpg', null, 9, true),
  ((select id from c where slug='pestanas'), 'Lifting', 'pestanas-lifting', null, null, 0, '/servicios/pestanas-lifting.jpg', null, 0, true),
  ((select id from c where slug='pestanas'), 'Permanente', 'pestanas-permanente', null, null, 0, '/servicios/pestanas-permanente.jpg', null, 1, true),
  ((select id from c where slug='pestanas'), 'Tinte', 'pestanas-tinte', null, null, 0, '/servicios/pestanas-tinte.jpg', null, 2, true),
  ((select id from c where slug='pestanas'), 'Extensiones clásicas', 'pestanas-extensiones-clasicas', null, null, 0, '/servicios/pestanas-extensiones-clasicas.jpg', null, 3, true),
  ((select id from c where slug='pestanas'), 'Volumen ruso', 'pestanas-volumen-ruso', null, null, 0, '/servicios/pestanas-volumen-ruso.jpg', null, 4, true),
  ((select id from c where slug='pestanas'), 'Mega volumen', 'pestanas-mega-volumen', null, null, 0, '/servicios/pestanas-mega-volumen.jpg', null, 5, true),
  ((select id from c where slug='pestanas'), 'Híbridas', 'pestanas-hibridas', null, null, 0, '/servicios/pestanas-hibridas.jpg', null, 6, true),
  ((select id from c where slug='pestanas'), 'Fox Eyes', 'pestanas-fox-eyes', null, null, 0, '/servicios/pestanas-fox-eyes.jpg', null, 7, true),
  ((select id from c where slug='pestanas'), 'Wispy', 'pestanas-wispy', null, null, 0, '/servicios/pestanas-wispy.jpg', null, 8, true),
  ((select id from c where slug='pestanas'), 'Retoques', 'pestanas-retoques', null, null, 0, '/servicios/pestanas-retoques.jpg', null, 9, true),
  ((select id from c where slug='maquillaje'), 'Social', 'maquillaje-social', null, null, 0, '/servicios/maquillaje-social.jpg', null, 0, true),
  ((select id from c where slug='maquillaje'), 'Novias', 'maquillaje-novias', null, null, 0, '/servicios/maquillaje-novias.jpg', null, 1, true),
  ((select id from c where slug='maquillaje'), 'Madrinas', 'maquillaje-madrinas', null, null, 0, '/servicios/maquillaje-madrinas.jpg', null, 2, true),
  ((select id from c where slug='maquillaje'), 'Fiesta', 'maquillaje-fiesta', null, null, 0, '/servicios/maquillaje-fiesta.jpg', null, 3, true),
  ((select id from c where slug='maquillaje'), 'Editorial', 'maquillaje-editorial', null, null, 0, '/servicios/maquillaje-editorial.jpg', null, 4, true),
  ((select id from c where slug='maquillaje'), 'Fotografía', 'maquillaje-fotografia', null, null, 0, '/servicios/maquillaje-fotografia.jpg', null, 5, true),
  ((select id from c where slug='maquillaje'), 'Televisión', 'maquillaje-television', null, null, 0, '/servicios/maquillaje-television.jpg', null, 6, true),
  ((select id from c where slug='maquillaje'), 'Corporativo', 'maquillaje-corporativo', null, null, 0, '/servicios/maquillaje-corporativo.jpg', null, 7, true),
  ((select id from c where slug='maquillaje'), 'Halloween', 'maquillaje-halloween', null, null, 0, '/servicios/maquillaje-halloween.jpg', null, 8, true),
  ((select id from c where slug='maquillaje'), 'Artístico', 'maquillaje-artistico', null, null, 0, '/servicios/maquillaje-artistico.jpg', null, 9, true),
  ((select id from c where slug='maquillaje'), 'Infantil', 'maquillaje-infantil', null, null, 0, '/servicios/maquillaje-infantil.jpg', null, 10, true),
  ((select id from c where slug='peluqueria'), 'Mujer', 'peluqueria-mujer', null, null, 0, '/servicios/peluqueria-corte-mujer.jpg', 'Corte', 0, true),
  ((select id from c where slug='peluqueria'), 'Hombre', 'peluqueria-hombre', null, null, 0, '/servicios/peluqueria-corte-hombre.jpg', 'Corte', 1, true),
  ((select id from c where slug='peluqueria'), 'Niño', 'peluqueria-nino', null, null, 0, '/servicios/peluqueria-corte-nino.jpg', 'Corte', 2, true),
  ((select id from c where slug='peluqueria'), 'Tinte', 'peluqueria-tinte', null, null, 0, '/servicios/peluqueria-tinte.jpg', 'Color', 3, true),
  ((select id from c where slug='peluqueria'), 'Balayage', 'peluqueria-balayage', null, null, 0, '/servicios/peluqueria-balayage.jpg', 'Color', 4, true),
  ((select id from c where slug='peluqueria'), 'Babylights', 'peluqueria-babylights', null, null, 0, '/servicios/peluqueria-babylights.jpg', 'Color', 5, true),
  ((select id from c where slug='peluqueria'), 'Mechas', 'peluqueria-mechas', null, null, 0, '/servicios/peluqueria-mechas.jpg', 'Color', 6, true),
  ((select id from c where slug='peluqueria'), 'Ombre', 'peluqueria-ombre', null, null, 0, '/servicios/peluqueria-ombre.jpg', 'Color', 7, true),
  ((select id from c where slug='peluqueria'), 'Corrección de color', 'peluqueria-correccion-de-color', null, null, 0, '/servicios/peluqueria-correccion-color.jpg', 'Color', 8, true),
  ((select id from c where slug='peluqueria'), 'Matización', 'peluqueria-matizacion', null, null, 0, '/servicios/peluqueria-matizacion.jpg', 'Color', 9, true),
  ((select id from c where slug='peluqueria'), 'Decoloración', 'peluqueria-decoloracion', null, null, 0, '/servicios/peluqueria-decoloracion.jpg', 'Color', 10, true),
  ((select id from c where slug='peluqueria'), 'Botox capilar', 'peluqueria-botox-capilar', null, null, 0, '/servicios/peluqueria-botox-capilar.jpg', 'Tratamientos', 11, true),
  ((select id from c where slug='peluqueria'), 'Keratina', 'peluqueria-keratina', null, null, 0, '/servicios/peluqueria-keratina.jpg', 'Tratamientos', 12, true),
  ((select id from c where slug='peluqueria'), 'Hidratación', 'peluqueria-hidratacion', null, null, 0, '/servicios/peluqueria-hidratacion.jpg', 'Tratamientos', 13, true),
  ((select id from c where slug='peluqueria'), 'Colágeno', 'peluqueria-colageno', null, null, 0, '/servicios/peluqueria-colageno.jpg', 'Tratamientos', 14, true),
  ((select id from c where slug='peluqueria'), 'Ácido hialurónico capilar', 'peluqueria-acido-hialuronico-capilar', null, null, 0, '/servicios/peluqueria-acido-hialuronico-capilar.jpg', 'Tratamientos', 15, true),
  ((select id from c where slug='peluqueria'), 'Reconstrucción', 'peluqueria-reconstruccion', null, null, 0, '/servicios/peluqueria-reconstruccion.jpg', 'Tratamientos', 16, true),
  ((select id from c where slug='peluqueria'), 'Células madre', 'peluqueria-celulas-madre', null, null, 0, '/servicios/peluqueria-celulas-madre.jpg', 'Tratamientos', 17, true),
  ((select id from c where slug='peluqueria'), 'Ampollas', 'peluqueria-ampollas', null, null, 0, '/servicios/peluqueria-ampollas.jpg', 'Tratamientos', 18, true),
  ((select id from c where slug='peluqueria'), 'Brushing', 'peluqueria-brushing', null, null, 0, '/servicios/peluqueria-brushing.jpg', 'Peinados', 19, true),
  ((select id from c where slug='peluqueria'), 'Ondas', 'peluqueria-ondas', null, null, 0, '/servicios/peluqueria-ondas.jpg', 'Peinados', 20, true),
  ((select id from c where slug='peluqueria'), 'Recogidos', 'peluqueria-recogidos', null, null, 0, '/servicios/peluqueria-recogidos.jpg', 'Peinados', 21, true),
  ((select id from c where slug='peluqueria'), 'Novias', 'peluqueria-novias', null, null, 0, '/servicios/peluqueria-peinado-novias.jpg', 'Peinados', 22, true),
  ((select id from c where slug='peluqueria'), 'Trenzas', 'peluqueria-trenzas', null, null, 0, '/servicios/peluqueria-trenzas.jpg', 'Peinados', 23, true),
  ((select id from c where slug='peluqueria'), 'Eventos', 'peluqueria-eventos', null, null, 0, '/servicios/peluqueria-eventos.jpg', 'Peinados', 24, true),
  ((select id from c where slug='barberia'), 'Corte', 'barberia-corte', null, null, 0, '/servicios/barberia-corte.jpg', null, 0, true),
  ((select id from c where slug='barberia'), 'Barba', 'barberia-barba', null, null, 0, '/servicios/barberia-barba.jpg', null, 1, true),
  ((select id from c where slug='barberia'), 'Perfilado', 'barberia-perfilado', null, null, 0, '/servicios/barberia-perfilado.jpg', null, 2, true),
  ((select id from c where slug='barberia'), 'Toallas calientes', 'barberia-toallas-calientes', null, null, 0, '/servicios/barberia-toallas-calientes.jpg', null, 3, true),
  ((select id from c where slug='barberia'), 'Camuflaje de canas', 'barberia-camuflaje-de-canas', null, null, 0, '/servicios/barberia-camuflaje-canas.jpg', null, 4, true),
  ((select id from c where slug='barberia'), 'Limpieza facial masculina', 'barberia-limpieza-facial-masculina', null, null, 0, '/servicios/barberia-limpieza-facial-masculina.jpg', null, 5, true),
  ((select id from c where slug='bronceado'), 'Spray tan', 'bronceado-spray-tan', null, null, 0, '/servicios/bronceado-spray-tan.jpg', null, 0, true),
  ((select id from c where slug='bronceado'), 'Autobronceado', 'bronceado-autobronceado', null, null, 0, '/servicios/bronceado-autobronceado.jpg', null, 1, true),
  ((select id from c where slug='bronceado'), 'Bronceado DHA', 'bronceado-bronceado-dha', null, null, 0, '/servicios/bronceado-dha.jpg', null, 2, true),
  ((select id from c where slug='bienestar'), 'Aromaterapia', 'bienestar-aromaterapia', null, null, 0, '/servicios/bienestar-aromaterapia.jpg', null, 0, true),
  ((select id from c where slug='bienestar'), 'Musicoterapia', 'bienestar-musicoterapia', null, null, 0, '/servicios/bienestar-musicoterapia.jpg', null, 1, true),
  ((select id from c where slug='bienestar'), 'Cromoterapia', 'bienestar-cromoterapia', null, null, 0, '/servicios/bienestar-cromoterapia.jpg', null, 2, true),
  ((select id from c where slug='bienestar'), 'Meditación guiada', 'bienestar-meditacion-guiada', null, null, 0, '/servicios/bienestar-meditacion-guiada.jpg', null, 3, true),
  ((select id from c where slug='bienestar'), 'Mindfulness', 'bienestar-mindfulness', null, null, 0, '/servicios/bienestar-mindfulness.jpg', null, 4, true),
  ((select id from c where slug='bienestar'), 'Relajación profunda', 'bienestar-relajacion-profunda', null, null, 0, '/servicios/bienestar-relajacion-profunda.jpg', null, 5, true),
  ((select id from c where slug='programas-premium'), 'Spa para parejas', 'programas-premium-spa-para-parejas', null, null, 0, '/servicios/programa-spa-parejas.jpg', null, 0, true),
  ((select id from c where slug='programas-premium'), 'Día de princesa', 'programas-premium-dia-de-princesa', null, null, 0, '/servicios/programa-dia-princesa.jpg', null, 1, true),
  ((select id from c where slug='programas-premium'), 'Día de reina', 'programas-premium-dia-de-reina', null, null, 0, '/servicios/programa-dia-reina.jpg', null, 2, true),
  ((select id from c where slug='programas-premium'), 'Bridal Spa', 'programas-premium-bridal-spa', null, null, 0, '/servicios/programa-bridal-spa.jpg', null, 3, true),
  ((select id from c where slug='programas-premium'), 'Cumpleaños Spa', 'programas-premium-cumpleanos-spa', null, null, 0, '/servicios/programa-cumpleanos-spa.jpg', null, 4, true),
  ((select id from c where slug='programas-premium'), 'Spa corporativo', 'programas-premium-spa-corporativo', null, null, 0, '/servicios/programa-spa-corporativo.jpg', null, 5, true),
  ((select id from c where slug='programas-premium'), 'Spa ejecutivo', 'programas-premium-spa-ejecutivo', null, null, 0, '/servicios/programa-spa-ejecutivo.jpg', null, 6, true),
  ((select id from c where slug='programas-premium'), 'Spa mamá e hija', 'programas-premium-spa-mama-e-hija', null, null, 0, '/servicios/programa-spa-mama-hija.jpg', null, 7, true),
  ((select id from c where slug='programas-premium'), 'Spa prenatal', 'programas-premium-spa-prenatal', null, null, 0, '/servicios/programa-spa-prenatal.jpg', null, 8, true),
  ((select id from c where slug='programas-premium'), 'Spa postparto', 'programas-premium-spa-postparto', null, null, 0, '/servicios/programa-spa-postparto.jpg', null, 9, true),
  ((select id from c where slug='programas-premium'), 'Spa masculino', 'programas-premium-spa-masculino', null, null, 0, '/servicios/programa-spa-masculino.jpg', null, 10, true),
  ((select id from c where slug='servicios-vip'), 'Membresías', 'servicios-vip-membresias', null, null, 0, '/servicios/vip-membresias.jpg', null, 0, true),
  ((select id from c where slug='servicios-vip'), 'Gift Cards', 'servicios-vip-gift-cards', null, null, 0, '/servicios/vip-gift-cards.jpg', null, 1, true),
  ((select id from c where slug='servicios-vip'), 'Paquetes mensuales', 'servicios-vip-paquetes-mensuales', null, null, 0, '/servicios/vip-paquetes-mensuales.jpg', null, 2, true),
  ((select id from c where slug='servicios-vip'), 'Planes anuales', 'servicios-vip-planes-anuales', null, null, 0, '/servicios/vip-planes-anuales.jpg', null, 3, true),
  ((select id from c where slug='servicios-vip'), 'Concierge de belleza', 'servicios-vip-concierge-de-belleza', null, null, 0, '/servicios/vip-concierge-belleza.jpg', null, 4, true),
  ((select id from c where slug='servicios-vip'), 'Beauty Coach', 'servicios-vip-beauty-coach', null, null, 0, '/servicios/vip-beauty-coach.jpg', null, 5, true),
  ((select id from c where slug='servicios-vip'), 'Diagnóstico facial digital', 'servicios-vip-diagnostico-facial-digital', null, null, 0, '/servicios/vip-diagnostico-facial.jpg', null, 6, true),
  ((select id from c where slug='servicios-vip'), 'Diagnóstico corporal', 'servicios-vip-diagnostico-corporal', null, null, 0, '/servicios/vip-diagnostico-corporal.jpg', null, 7, true),
  ((select id from c where slug='servicios-vip'), 'Seguimiento personalizado', 'servicios-vip-seguimiento-personalizado', null, null, 0, '/servicios/vip-seguimiento-personalizado.jpg', null, 8, true),
  ((select id from c where slug='servicios-vip'), 'Cabinas privadas VIP', 'servicios-vip-cabinas-privadas-vip', null, null, 0, '/servicios/vip-cabinas-privadas.jpg', null, 9, true),
  ((select id from c where slug='servicios-vip'), 'Servicio a domicilio', 'servicios-vip-servicio-a-domicilio', null, null, 0, '/servicios/vip-servicio-domicilio.jpg', null, 10, true),
  ((select id from c where slug='servicios-vip'), 'Atención para eventos', 'servicios-vip-atencion-para-eventos', null, null, 0, '/servicios/vip-atencion-eventos.jpg', null, 11, true)
on conflict (slug) do update set
  categoria_id = excluded.categoria_id,
  nombre = excluded.nombre,
  imagen_url = coalesce(excluded.imagen_url, spanails.servicios.imagen_url),
  grupo = excluded.grupo,
  orden = excluded.orden,
  activo = true;

-- 4) Verificación
select count(*) as categorias from spanails.categorias where icono is not null;
select count(*) as servicios from spanails.servicios;